(function(g){var window=this;var z4=function(a){var b={format:a.B,languageCode:a.A,languageName:a.D,displayName:g.WH(a),kind:a.C,name:a.F,id:a.Ia,is_servable:a.M,is_default:a.isDefault,is_translateable:a.H,vss_id:a.G};a.o&&(a=a.o,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.o,id:a.id,is_default:a.isDefault});return b},A4=function(a){return a.o?a.o.languageCode:a.A},yBa=function(a,b){var c=new g.VH;
c.A=a.A;c.D=a.D;c.F=a.F;c.C=a.C;c.isDefault=!1;c.H=a.H;c.G=a.G;c.J=a.J;c.o=b;return c},B4=function(a){if(!zBa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(ABa,"#$1$1$2$2$3$3"));a=a.toLowerCase();return[(0,window.parseInt)(a.substr(1,2),16),(0,window.parseInt)(a.substr(3,2),16),(0,window.parseInt)(a.substr(5,2),16)]},C4=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.UQ.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.D=f;this.A=k},D4=function(a,b,c,d,e){g.UQ.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.A=[]},F4=function(a){a=void 0===a?{}:a;
var b="_"+E4++;return new D4(0,0x8000000000000,0,b,a)},G4=function(a,b,c,d,e,f){var k={};
g.Ga(k,b);g.Ga(k,a.params);g.Ga(k,c);var l={};g.Ga(l,b.ob);a.params.ob&&g.Ga(l,a.params.ob);g.Ga(l,c.ob);k.ob=l;g.W.call(this,{I:"div",N:"caption-window",U:{id:"caption-window-"+a.id,dir:1==k.al?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},P:[{I:"span",N:"captions-text"}]});this.D=[];this.M=!1;this.H=a;this.G=[];this.J=[];this.Ba=e;this.za=f;this.F=null;this.aa=.96*e;this.ka=.96*f;this.A=k;this.va=c;this.C=this.o["captions-text"];this.oa=null!=this.C.style["box-decoration-break"]||
null!=this.C.style["-webkit-box-decoration-break"];this.O=d/360*16;this.type=0;this.ga=this.O*BBa(l);a=new g.TF(this.element,!0);g.N(this,a);a.subscribe("dragstart",this.GP,this);a.subscribe("dragmove",this.FP,this);a.subscribe("dragend",this.EP,this);this.ia=this.ha=0;a="";this.A.ql&&(a=B4(this.A.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.A.ql+")");b={"background-color":a,display:!1===this.A.isVisible?"none":"","text-align":CBa[this.A.textAlign]};this.oa&&(b["border-radius"]=a?this.ga/
8+"px":"");g.Ah(this.element,b);switch(this.A.Of){case 0:case 1:case 2:g.T(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.T(this.element,"ytp-caption-window-bottom")}},BBa=function(a){var b=1+.25*(a.Oj||0);
if(0==a.offset||2==a.offset)b*=.8;return b},H4=function(a,b){var c={},d=b.background?b.background:a.A.ob.background;
if(null!=b.nf||b.background){var e=null!=b.nf?b.nf:a.A.ob.nf;d=B4(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.oa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ga/8+"px")}if(null!=b.Oj||null!=b.offset)c["font-size"]=a.O*BBa(b)+"px";d=1;e=b.color||a.A.ob.color;if(b.color||null!=b.ci)e=B4(e),d=null==b.ci?a.A.ob.ci:b.ci,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=e,c.fill=e;var f=b.wi;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";
b.My&&(k=e=b.My);var l=a.O/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';
break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.GE()?'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e=
'"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.A.ob.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.wf&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");b.Bt&&(c.visibility="hidden");return c},DBa=function(a,b,c){a.M=a.M||!!c;
var d={};g.Ga(d,a.A.ob);g.Ga(d,c||b.A);g.Ga(d,a.va.ob);c=a.G[0];if(c&&d.background==c.background&&d.nf==c.nf&&!!d.Bt==!!c.Bt&&d.wi==c.wi){var e;for(e=0;e<a.G.length;e++)if(g.dc(d,a.G[e])){var f=a.J[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.Hd("SPAN");g.Ah(f,H4(a,e));a.J[0].appendChild(f);e=1}a.J.length=e;a.G.length=e}else a.J.length=0,a.G.length=0,f=g.Hd("SPAN"),g.Ah(f,H4(a,d)),a.C.appendChild(f);a.F&&a.F.parentNode!=f&&(g.Od(a.F),f.appendChild(a.F));c=(k=g.w(b.text))?b.text.split("\n"):
[b.text];for(e=0;e<c.length;e++){var l=c[e];if(0<e||0==a.D.length||!b.D){if(0<e||0!=a.D.length){var m=g.Hd("BR");f.appendChild(m)}f.appendChild(g.Id("\u00a0"));a.F=g.Id("\u00a0");f.appendChild(a.F)}l&&(m=a.F,m.parentNode&&m.parentNode.insertBefore(k?g.Id(l):l,m))}a.G.push(d);a.J.push(f);a.D.push(b)},EBa=function(){},J4=function(){this.C=this.A=this.mode=this.B=0;
this.D=new I4(this);this.F=new I4(this);this.o=[];this.clear()},GBa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Un:a,
Vn:b,result:0};a=FBa[a];b=FBa[b];if(a&128){if(!(b&128)&&0!=c.o&&c.A==b)return{Un:a,Vn:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Un:a,Vn:b,result:2};return{Un:a,Vn:b,result:3}},IBa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.C&&a.reset(),a.D.o.clear(),a.F.o.clear()):(a.C=0,HBa(a.D,b,c,d))},JBa=function(a,b){a.o.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.A=d.time;0==d.type?IBa(a,d.Hy,d.Iy,b):1==d.type&&a.B&496&&HBa(a.F,d.Hy,d.Iy,b)}a.o.length=0},K4=function(){this.o=0},L4=function(){this.A=this.B=this.o=0},M4=function(){this.timestamp=this.Ee=0},N4=function(a){this.B=[];
for(var b=0;15>=b;b++){this.B[b]=[];for(var c=0;32>=c;c++)this.B[b][c]=new M4}this.o=this.A=this.row=0;this.style=new K4;this.D=a;this.C=0},O4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.D.A+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.B[m][p];
if(0!=r.Ee){0==c&&(c=m,d=p);n=String.fromCharCode(r.Ee);var v=r.timestamp;v<e&&(e=v);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Ee||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.A+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.B[k][m],r=p.Ee,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),v=p.timestamp,v<=e&&(e=v),l+=n,p.reset()),32==m||0==r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},OBa=function(a,b){switch(a){case 0:return KBa[(b&127)-32];
case 1:return LBa[b&15];case 2:return MBa[b&31];case 3:return NBa[b&31]}return 0},P4=function(a){return a.B[a.row][a.A]},Q4=function(a,b,c){2<=b&&1<a.A&&(--a.A,P4(a).Ee=0);
var d=P4(a);d.timestamp=a.D.A+0;d.Ee=OBa(b,c);32>a.A&&a.A++},PBa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.B[b+e][f].no(a.B[c+e][f])},R4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},S4=function(a){a.row=0<a.o?a.o:1;
a.A=1;R4(a,0,15)},T4=function(a){this.C=a;
this.D=0;this.style=new K4;this.F=new N4(a);this.G=new N4(a);this.H=new N4(a);this.A=this.F;this.B=this.G;this.o=this.A},U4=function(a,b,c){var d=a.A,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:O4(d,c),S4(a.A),S4(a.B),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.C.mode=1<<d.C;e?d.A=1:d.o!=b&&(d.o>b?(O4(d,c),R4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},QBa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.C.mode=1<<a.o.C},RBa=function(a){a.style.set(4);
a.o=a.H;a.o.style=a.style;a.C.mode=1<<a.o.C},I4=function(a){this.A=a;
this.o=new L4;this.D=0;this.B=new T4(a);this.F=new T4(a);this.C=this.B},HBa=function(a,b,c,d){a.o.update();
b=GBa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Un;c=b.Vn;if(32<=e||!e)a.A.mode&a.A.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.o,b&96&&Q4(a,0,b),c&96&&Q4(a,0,c),0!=b&&0!=c&&3==a.style.o&&O4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.B=e,b.A=c,b.o=2,b=e&8?a.F:a.B,a.C=b,a.A.mode=1<<(a.D<<2)+(b.D<<1)+(4==b.style.o?1:0),(a.A.mode|1<<(a.D<<2)+(b.D<<1)+(4!=b.style.o?1:0))&a.A.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;PBa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));R4(c,b,e)}}c.row=d;c.A=a+1}else switch(e&7){case 1:switch(c&112){case 32:Q4(b.o,0,32);break a;case 48:57==c?(b=b.o,P4(b).Ee=0,32>b.A&&b.A++):Q4(b.o,1,c&15)}break;case 2:c&32&&Q4(b.o,2,c&31);break;case 3:c&32&&Q4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:QBa(b);break;
case 33:b=b.o;1<b.A&&(--b.A,P4(b).Ee=0);break;case 36:b=b.o;d=P4(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.B[a][c]==d){for(;32>=c;c++)b.B[a][c].reset();break}break;case 37:U4(b,2,d);break;case 38:U4(b,3,d);break;case 39:U4(b,4,d);break;case 40:Q4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.A;b.o.o=0;b.o.style=b.style;b.C.mode=1<<b.o.C;break;case 42:d=b.H;d.o=15;d.style.set(4);S4(d);RBa(b);break;case 43:RBa(b);break;case 44:a=b.A;switch(b.style.get()){case 1:case 2:case 3:O4(a,d)}R4(a,0,15);break;
case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.A=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;O4(a,d);PBa(a,b,b+1,a.o-1);R4(a,a.row,1)}break;case 46:R4(b.B,0,15);break;case 47:O4(b.A,d);d=b.B;a=b.C.A+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.B[c][e].timestamp=a;d=b.B;b.B=b.A;b.A=d;QBa(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.o,32<(b.A+=c&3)&&(b.A=32)}}},V4=function(){},W4=function(a){this.A=a;
this.o=null},TBa=function(a,b,c){var d=a.getAttribute("t");
d=d?(0,window.parseInt)(d,10):1E3*(0,window.parseFloat)(a.getAttribute("start")||0);var e=a.getAttribute("d");e=e?(0,window.parseFloat)(e):1E3*(0,window.parseFloat)(a.getAttribute("dur")||0);b=a.getAttribute("w")||b;var f=!!a.getAttribute("append"),k=f?6:5;a=g.fs("<html>"+(a.firstChild&&a.firstChild.nodeValue||"")+"</html>");SBa(d,e,k,b,f,a.firstChild,{},c)},SBa=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.wf=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");X4.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new C4(a,b,c,d,n.nodeValue,e||0<m,g.Zb(k)?void 0:k));else{var p={};g.Ga(p,k);SBa(a,b,c,d,e||0<m,n,p,l)}}},Y4=function(){this.A={};
this.o=null},Z4=function(a){this.C={};
this.J={};this.K={};this.D="_"+E4++;this.F=a;this.H={};this.A=this.o=null;this.G=!0},$4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},a5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},b5=function(a,b){var c=$4(a,b);
if(void 0!=c)return c},c5=function(a,b){var c=a.getAttribute(b);
if(null!=c)return X4.test(c),c},UBa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ga(c,d?a.K[d]:a.F);d=b5(b,"mh");null!=d&&(c.wu=d);d=b5(b,"ju");null!=d&&(c.textAlign=d);d=b5(b,"pd");null!=d&&(c.al=d);d=c5(b,"wfc");null!=d&&(c.windowColor=d);d=$4(b,"wfo");void 0!=d&&(c.ql=d/255);return c},VBa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ga(c,a.J[d]);d=b5(b,"ap");null!=d&&(c.Of=d);d=$4(b,"cc");null!=d&&(c.qs=d);d=$4(b,"ah");null!=d&&(c.Ve=d);d=$4(b,"rc");null!=d&&(c.yq=d);d=$4(b,"av");null!=d&&(c.sg=d);return c},WBa=function(a,b,c,d){var e={};
g.Ga(e,VBa(a,b));g.Ga(e,UBa(a,b));d?g.dc(e,a.F)?(d=a.D,e=a.F):d="_"+E4++:d=b.getAttribute("id")||"_"+E4++;a=$4(b,"t")+c;b=$4(b,"d")||0x8000000000000;return new D4(a,b,0,d,e)},d5=function(a,b,c){this.G=c;
this.version=this.F=this.C=this.o=0;this.A=new window.DataView(a);this.B=[]},e5=function(a){var b=a.o;
a.o+=1;return a.A.getUint8(b)},f5=function(a){var b=a.o;
a.o+=4;return a.A.getUint32(b)},g5=function(a,b){this.A=a;
this.track="CC3"==b.D?4:0;this.o=new J4;this.o.B=1<<this.track},YBa=function(a){if(g.w(a))return!1;
a=new d5(a,8,0);return XBa(a)},XBa=function(a){if(!(a.o<a.A.byteLength)||1380139777!=f5(a))return!1;
a.version=e5(a);if(1<a.version)return!1;e5(a);e5(a);e5(a);return!0},ZBa=function(){this.A=[];
this.o=[]},h5=function(a,b){return b?a.o.concat(a.A):a.o},i5=function(a,b){switch(b.C){case "asr":var c=a.A;
g.Ka(c,(0,g.A)(b.K,b))||c.push(b);break;default:c=a.o,g.Ka(c,(0,g.A)(b.K,b))||c.push(b)}},j5=function(){},$Ba=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.wf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType)p=new C4(b,c,d,e.id,p.nodeValue,f||0<n,g.Zb(l)?void 0:l),m.push(p),e.A.push(p);else{var r={};g.Ga(r,l);$Ba(a,b,c,d,e,!0,p,r,m)}}},k5=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},aCa=function(a,b,c,d){d=Object.assign({wu:0},d);
return new D4(a,b,c,"_"+E4++,d)},l5=function(a){g.M.call(this);
this.QA=!!a;this.A=new ZBa;this.G=[];this.o=null},cCa=function(a){var b={};
if(a=A4(a))b.lang=a,bCa.test(a)&&(b.al=1);return b},dCa=function(a,b,c,d,e){d=d||0;
e=e||0;if(!g.w(b)){var f=new window.DataView(b);if(1718909296==f.getUint32(4)&&(f=g.tK(f,1835295092),b=b.slice(f.dataOffset,f.dataOffset+f.size),!YBa(b)&&(b=g.he(new window.Uint8Array(b)),!b)))return[]}if(g.w(b)){if("WEBVTT"==b.substring(0,6))return a.o||(a.o=new j5),a.o.B(b,d);b=g.fs(b);if(!b||!b.firstChild)return[];if(!a.o)if("timedtext"==b.firstChild.tagName)3==(0,window.parseInt)(b.firstChild.getAttribute("format"),10)?a.o=new Z4(cCa(c)):a.o=new Y4;else try{return a.o=new W4(cCa(c)),a.o.B(b,d)}catch(k){return g.bE(k),
a.o=null,[]}return a.o.B(b,d)}try{if(YBa(b))return a.o||(a.o=new g5(e,c)),a.o.B(b,d)}catch(k){g.bE(k),a.o=null}return[]},m5=function(a){l5.call(this,a.bo);
this.C=void 0;this.B=null;this.G=a.captionTranslationLanguages},n5=function(){this.ub=[]},o5=function(a,b,c,d,e,f){g.M.call(this);
this.L=a;this.C=b;this.F=new n5;this.o=null;this.J=d;this.M=f;this.B=this.A=null;this.H=c;this.G=e||!1;this.K=new g.iu(this.jB,1E3,this);g.N(this,this.K);this.D=new g.OF(this);g.N(this,this.D);this.D.R(b,"seekto",this.oC);this.oC(b.getCurrentTime());this.jB()},eCa=function(a,b){var c=a.o;
a.o=g.Ia(a.H.Jg(b).o);c!=a.o&&a.M&&a.M()},fCa=function(a,b){var c=g.NL(b,a.L,{}).Wa(),d={format:"RAW",
withCredentials:!0};a.G&&(d.responseType="arraybuffer");a.B=g.UE(c,d,3,100).then((0,g.A)(a.wU,a));a.A=b;c=a.F;d=a.A.o[0].ya;var e=g.db(c.ub,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.ub[e-1]&&e<c.ub.length&&1==c.ub[e]-d?(g.Sa(c.ub,e),g.Sa(c.ub,e-1)):0<e&&1==d-c.ub[e-1]?c.ub[e-1]=d:e<c.ub.length&&1==c.ub[e]-d?c.ub[e]=d:(g.$a(c.ub,e,0,d),g.$a(c.ub,e+1,0,d)))},p5=function(a,b){l5.call(this);
this.B=a;this.C=b;this.D=null;this.F=!1},gCa=function(a,b){if(b in a.B.o)return a.B.o[b];
if(g.oM(a.B))for(var c in a.B.o){var d=a.B.o[c];if(g.mI(d.info.mimeType)&&("386"!=c||!g.Y(a.C).experiments.o("html5_manifestless_captions_fmt3_killswitch")))return d}return null},q5=function(a,b){return a.Ca&&null!=a.pa||g.Y(b).Ma&&null!=a.pa&&null!=a.pa.o.rawcc},r5=function(a,b,c,d,e,f){G4.call(this,a,b,c,d,e,f);
this.type=1},s5=function(a,b,c,d,e,f){G4.call(this,a,b,c,d,e,f);
g.T(this.element,"ytp-caption-window-rollup");this.type=2;this.L=this.T=0;this.Z=this.K=window.NaN;this.sa=null;this.da=new g.iu(this.BU,433,this);g.N(this,this.da)},t5=function(a){if(!a.T){var b=g.Hd("SPAN");
g.Ah(b,H4(a,a.A.ob));a.C.appendChild(b);b.appendChild(g.Id("M"));var c=b.offsetHeight,d=g.Hd("BR");b.appendChild(d);b.appendChild(g.Id("M"));a.T=b.offsetHeight-c;a.C.removeChild(b)}return a.T},hCa=function(a){if((0,window.isNaN)(a.K)){var b=a.A.qs;
if(b){var c=g.Hd("SPAN");g.Wd(c,"\u2013".repeat(b));g.Ah(c,H4(a,a.A.ob));a.C.appendChild(c);a.K=c.offsetWidth;a.C.removeChild(c)}else a.K=0}return a.K},u5=function(a,b,c,d){l5.call(this,d);
c=c||g.nE(a).hl||"";c=c.split("_").join("-");this.D=g.pE(a,{hl:c});this.C=b;this.F={};this.B=null},x5=function(a){g.JU.call(this,a);
this.C=g.Y(a);this.B=a.getVideoData();this.oa=g.kU(a);this.K=a;var b=null,c=g.yD("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.hD(c));this.aa=b;this.F={ob:{}};this.H={ob:{}};this.O=[];this.T={};this.ba={};this.M=!1;this.sa="1"==this.B.qc.cc_auto_caps||"1"==this.C.Zb.cc_auto_caps;b="3"==this.C.C&&!!g.DU(a)&&g.DU(a).jn();this.G=(c=!this.C.experiments.o("web_player_native_controls_live_captions_fix_killswitch"))?b&&!this.B.Ca:b;this.ia=c&&b&&this.B.Ca&&q5(this.B,this.K);c=b=this.A=this.D=
this.J=this.L=this.Z=this.ka=null;this.G||(b=new g.fu(this.QF,void 0,this),g.N(this,b),c=new g.iu(this.jW,2E3,this),g.N(this,c));this.da=b;this.ha=c;this.Y=new g.OF(this);g.N(this,this.Y);this.G||this.Y.R(a,"resize",this.Aw);this.Y.R(a,"onPlaybackAudioChange",this.vR);this.Y.R(a,"crn_captions",this.GN,this);this.Y.R(a,"crx_captions",this.HN,this);v5(this,w5(this,"display-settings")||{})},iCa=function(a){if(1==a.C.mh||1==a.B.mh||"alwayson"==g.CP(a.B,"yt:cc"))return!0;
if(2==a.C.mh){var b=w5(a,"module-enabled");if(null!=b)return!!b}if(a.B.captionTracks.length)var c=a.o.getAudioTrack().es;return"ON"==c||"on"==g.CP(a.B,"yt:cc")},y5=function(a,b){if(a.A&&(void 0===b||!b)||!a.B.captionTracks.length)return!1;
var c=a.o.getAudioTrack();return!!c.Co||"FORCED_ON"==c.es},A5=function(a,b){if(a.D){var c=h5(a.D.A,b||a.sa);
if(a.J&&a.J.o)return a.J.o;for(var d=[a.B.lh,a.C.lh,g.CP(a.B,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(A4(c[f])==d[e])return c[f];return a.J&&a.J.Cs?a.J.Cs:(d=c.find(function(a){return a.isDefault}))?d:c[0]||z5(a)}return null},z5=function(a){return a.J&&a.J.Co},jCa=function(a,b){for(var c=g.DU(a.K).na().textTracks,d=a.A.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},C5=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.M=c,a.M&&B5(a,"module-enabled",!!b));a.A=b;y5(a)&&(a.A=z5(a));a.load(d)},kCa=function(a){if(a.A!=z5(a)){if(a.M&&!g.sN(a.C)&&!g.zN(a.C)){g.lu(a.ha);
var b=F4({Of:0,Ve:5,sg:5,yq:2,textAlign:0,al:0,lang:"no"});a.Z=[b];var c=["Klikk p\u00e5 "," for \u00e5 se innstillingene"];if(!a.ka){var d=new g.yH(g.ira());g.N(a,d);a.ka=d.element}d=b.end-b.start;var e=g.WH(a.A);e&&a.Z.push(new C4(b.start,d,0,b.id,e));a.Z.push(new C4(b.start,d,0,b.id,c[0]),new C4(b.start,d,0,b.id,a.ka,!0),new C4(b.start,d,0,b.id,c[1],!0));g.xU(a.o,a.Z);g.ju(a.ha)}if(a.M||g.sN(a.C))B5(a,"module-enabled",!0),a.J&&(a.J.o=a.A);(a=g.iU(a.o.app))&&a.F&&g.VP(a.F.B)}},lCa=function(a,b){var c=
g.o_(a.oa,!0).height;
if(!c)return null;var d=a.oa.Sa();switch(null!=b.params.wu?b.params.wu:b.params.XW?2:1<b.A.length?1:0){case 1:return new r5(b,a.F,a.H,c,d.width,d.height);case 2:return new s5(b,a.F,a.H,c,d.width,d.height);default:return new G4(b,a.F,a.H,c,d.width,d.height)}},v5=function(a,b,c){var d=D5.ob;
a.F={};g.Ga(a.F,D5);a.F.ob={};g.Ga(a.F.ob,d);a.H={ob:{}};var e=b.backgroundOverride?a.H:a.F,f=b.background||d.background;X4.test(f);e.ob.background=f;e=b.colorOverride?a.H:a.F;f=b.color||d.color;X4.test(f);e.ob.color=f;e=b.windowColorOverride?a.H:a.F;f=b.windowColor||D5.windowColor;X4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.H:a.F;f=b.backgroundOpacity;null==f&&(f=d.nf);e.ob.nf=f;e=b.fontSizeIncrementOverride?a.H:a.F;f=b.fontSizeIncrement;null==f&&(f=d.Oj);e.ob.Oj=f;f=b.fontStyleOverride?
a.H:a.F;e=b.fontStyle;null==e&&(e=d.bold&&d.wf?3:d.bold?1:d.wf?2:0);f=f.ob;switch(e){case 1:f.bold=!0;delete f.wf;break;case 2:delete f.bold;f.wf=!0;break;case 3:f.bold=!0;f.wf=!0;break;default:delete f.bold,delete f.wf}e=b.textOpacityOverride?a.H:a.F;f=b.textOpacity;null==f&&(f=d.ci);e.ob.ci=f;e=b.windowOpacityOverride?a.H:a.F;f=b.windowOpacity;null==f&&(f=D5.ql);e.ql=f;e=b.charEdgeStyleOverride?a.H:a.F;f=b.charEdgeStyle;null==f&&(f=d.wi);e.ob.wi=f;e=b.fontFamilyOverride?a.H:a.F;f=b.fontFamily;null==
f&&(f=d.fontFamily);e.ob.fontFamily=f;a.loaded&&a.Aw();c&&B5(a,"display-settings",b)},nCa=function(a,b){if(b&&!a.L){var c=F4({al:0,
lang:"no"});a.L=[c,new C4(c.start,c.end-c.start,0,c.id,"Tekstingen ser slik ut")];g.xU(a.o,a.L)}else!b&&a.L&&(mCa(a,a.L),a.L=null)},mCa=function(a,b){g.zU(a.o,b);
(0,g.C)(b,function(a){g.Ta(this.O,a)},a);
a.da.Zj()},oCa=function(a,b){return a&&g.w(a)&&X4.test(a)?a:b},pCa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},qCa=function(a,b){return g.ta(a)&&!(0,window.isNaN)(a)?g.gd(a,-2,4):b},w5=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},B5=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.DX.prototype.Hj=g.ca(9,function(){for(var a=g.ud(window.document,"track",void 0,this.o),b=0;b<a.length;b++)g.Od(a[b])});
g.d_.prototype.Hj=g.ca(8,function(){this.o.Hj()});
g.DX.prototype.jn=g.ca(7,function(){return!!this.o.textTracks});
g.d_.prototype.jn=g.ca(6,function(){return this.o.jn()});
g.DX.prototype.wl=g.ca(5,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.d_.prototype.wl=g.ca(4,function(a){this.o.wl(a)});
g.aK.prototype.No=g.ca(2,function(a){return(a=this.qh(a))?a.A:0});
g.eM.prototype.No=g.ca(1,function(){return 0});
g.VH.prototype.K=g.ca(0,function(a){return a?this.toString()==a.toString():!1});
var bCa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,ABa=/#(.)(.)(.)/,zBa=/^#(?:[0-9a-f]{3}){1,2}$/i,X4=/^#(?:[0-9a-f]{3}){1,2}$/i;var CBa=["left","right","center"];var D5={windowColor:"#080808",ql:0,textAlign:2,Of:7,Ve:50,sg:100,ob:{background:"#080808",nf:.75,wi:0,color:"#fff",fontFamily:4,Oj:0,ci:1,offset:1}};g.t(C4,g.UQ);g.t(D4,g.UQ);var E4=0;g.t(G4,g.W);g.h=G4.prototype;g.h.GP=function(a,b){var c=g.Rh(this.element,this.element.parentElement);this.ha=a-c.x;this.ia=b-c.y;g.T(this.element,"ytp-dragging")};
g.h.FP=function(a,b){var c=g.Uh(this.element),d=a-this.ha-.02*this.Ba,e=b-this.ia-.02*this.za,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.gd(f,0,2));var k=(e+c.height/2)/this.ka*3;k=Math.floor(g.gd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.gd(d,0,1);c=(e+k/2*c.height)/this.ka;c=100*g.gd(c,0,1);this.H.params.Of=l;this.H.params.sg=c;this.H.params.Ve=d;this.A.Of=l;this.A.sg=c;this.A.Ve=d;this.GE()};
g.h.EP=function(){g.zq(this.element,"ytp-dragging")};
g.h.GE=function(){this.nj(this.D)};
g.h.Wb=function(){return this.type};
g.h.nj=function(a){var b=Math.min(this.Tz(),this.aa),c=this.Sz();g.Ah(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Tr(a);a={transform:"",top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var d=.96*this.A.Ve+2,e=this.A.Of;switch(e){case 0:case 3:case 6:a.left=d+"%";break;case 1:case 4:case 7:a.left=d+"%";d=this.C.offsetWidth;b||d?(b=b||d+1,a.width=b+"px",a["margin-left"]=
b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-d+"%"}b=.96*this.A.sg+2;switch(e){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.Ah(this.element,a)};
g.h.Tr=function(a){var b;for(b=0;b<a.length&&a[b]==this.D[b];b++);if(this.M||this.D.length>b)b=0,this.M=!1,this.D=[],this.G=[],this.J=[],this.F=null,g.Ld(this.C);for(;b<a.length;b++)DBa(this,a[b])};
g.h.Tz=function(){return 0};
g.h.Sz=function(){return 0};EBa.prototype.D=function(){};J4.prototype.clear=function(){this.C=this.A=this.mode=0;this.o=[];this.reset()};
J4.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var FBa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];K4.prototype.set=function(a){this.o=a};
K4.prototype.get=function(){return this.o};
L4.prototype.clear=function(){this.o=0};
L4.prototype.update=function(){this.o=2==this.o?1:0};
L4.prototype.matches=function(a,b){return 0!=this.o&&a==this.B&&b==this.A};
M4.prototype.no=function(a){this.Ee=a.Ee;this.timestamp=a.timestamp};
M4.prototype.reset=function(){this.timestamp=this.Ee=0};
N4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0==d.Ee?a+"_":a+String.fromCharCode(d.Ee)}a+="\n"}return a};
N4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.o=0;this.A=this.row=1};
var KBa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],LBa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],MBa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],NBa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];T4.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.A=this.F;this.B=this.G;this.o=this.A;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.H.reset((a<<2)+(b<<1)+1)};
I4.prototype.reset=function(a){this.D=a;this.o.clear();this.C=this.B;this.B.reset(a,0);this.F.reset(a,1)};V4.prototype.reset=function(){};g.t(W4,V4);W4.prototype.B=function(a){var b=[];this.o||(this.o=F4(this.A),b.push(this.o));a=Array.from(a.firstChild.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())TBa(c.value,this.o.id,b);return b};g.t(Y4,V4);
Y4.prototype.B=function(a){var b=[];this.o||(this.o=F4(),this.A[this.o.id]=this.o,b.push(this.o));for(a=a.firstChild.firstChild;a;){switch(a.tagName){case "window":var c=a,d=c.getAttribute("id");a:{var e=c,f=this.A[d];if(e.getAttribute("t")||e.getAttribute("start")){c=e.getAttribute("start")?1E3*(0,window.parseFloat)(e.getAttribute("start")):(0,window.parseInt)(e.getAttribute("t"),10);f&&(f.end>=c?f.end=c:f=null);switch(e.getAttribute("op")){case "kill":c=null;break a;case "define":f=null}f||(f=F4());
var k={};f&&(g.Ga(k,f.params),f=f.params.ob)&&(k.ob={},g.Ga(k.ob,f));e.getAttribute("rc")&&(k.yq=(0,window.parseInt)(e.getAttribute("rc"),10));e.getAttribute("cc")&&(k.qs=(0,window.parseInt)(e.getAttribute("cc"),10));e.getAttribute("ap")&&(f=(0,window.parseInt)(e.getAttribute("ap"),10),k.Of=0>f||8<f?7:f);e.getAttribute("ah")&&(k.Ve=(0,window.parseInt)(e.getAttribute("ah"),10));e.getAttribute("av")&&(k.sg=(0,window.parseInt)(e.getAttribute("av"),10));e.getAttribute("vs")&&(k.isVisible=!!e.getAttribute("vs"));
e.getAttribute("ju")&&(k.textAlign=(0,window.parseInt)(e.getAttribute("ju"),10));e.getAttribute("pd")&&(k.al=1,0==(0,window.parseInt)(e.getAttribute("pd"),10)&&(k.al=0));e.getAttribute("bc")&&(k.ob||(k.ob={}),k.ob.backgroundColor=e.getAttribute("bc"));e.getAttribute("bo")&&(k.ob||(k.ob={}),k.ob.nf=(0,window.parseInt)(e.getAttribute("bo"),10)/100);e.getAttribute("fc")&&(k.ob||(k.ob={}),k.ob.color=e.getAttribute("fc"));e.getAttribute("sd")&&(k.XW=(0,window.parseInt)(e.getAttribute("sd"),10));f=(0,window.parseInt)(e.getAttribute("d"),
10)||1E3*(0,window.parseFloat)(e.getAttribute("dur"))||0x8000000000000;e=e.getAttribute("id")||"_"+E4++;c=new D4(c,f,0,e,k)}else c=null}this.A[d]=c;b.push(c);break;case "text":for(d=[],TBa(a,this.o.id,d),d=g.q(d),c=d.next();!c.done;c=d.next())c=c.value,this.A[c.windowId]&&b.push(c)}a=a.nextSibling}return b};g.t(Z4,V4);Z4.prototype.reset=function(){this.H={};this.A=this.o=null;this.G=!0};
Z4.prototype.B=function(a,b){a.firstChild.getAttribute("format");b=b||0;Number.isFinite(b);var c=Array.from(a.firstChild.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.C,l={},m=c.getAttribute("p");m&&g.Ga(l,this.C[m]);m=a5(c,"b");null!=
m&&(l.bold=m);m=a5(c,"i");null!=m&&(l.wf=m);m=a5(c,"u");null!=m&&(l.underline=m);m=b5(c,"et");null!=m&&(l.wi=m);m=b5(c,"of");null!=m&&(l.offset=m);m=c5(c,"bc");null!=m&&(l.background=m);m=c5(c,"ec");null!=m&&(l.My=m);m=c5(c,"fc");null!=m&&(l.color=m);m=b5(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=$4(c,"sz");void 0!=m&&(l.Oj=m/100-1);m=$4(c,"bo");void 0!=m&&(l.nf=m/255);c=$4(c,"fo");void 0!=c&&(l.ci=c/255);k[d]=l;break;case "ws":d=c.getAttribute("id");this.K[d]=UBa(this,c);break;case "wp":d=c.getAttribute("id"),
this.J[d]=VBa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=WBa(this,d,e,!1);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.D;m=!!a5(d,"a");n=($4(d,"t")||0)+n;var p=$4(d,"d")||5E3;m||(!this.G&&this.A&&this.A.windowId==l&&this.A.end>n&&(this.A.end=n),this.A&&"\n"==this.A.text&&(this.A.text=
""));var r=m?6:5,v=this.C[d.getAttribute("p")],D=d.childNodes;D.length&&(this.G=null!=d.getAttribute("d"));for(var H=0;H<D.length;H++){var L=D[H];0<H&&(m=!0);var S=void 0;1==L.nodeType&&(S=L);if(S&&"s"==S.tagName){var ha=S;L=n;S=p;var Za=l,jb=m,Yc=r,zf=ha.textContent?ha.textContent:"",nb=this.C[ha.getAttribute("p")];ha=$4(ha,"t")||0;L=new C4(L+ha,S-ha,Yc,Za,zf,jb,nb)}else L=new C4(n,p,r,l,L.textContent||"",m,v);k.push(L);this.A=L}if(0<k.length)for(k[0].windowId==this.D&&(this.o=WBa(this,d,e,!0),c.push(this.o)),
d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.A.push(k),c.push(k)}e=c}else e=[];return e};g.t(d5,EBa);d5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+E4++;c=c/1E3-this.G;d=d/1E3-this.G;a=new D4(c,d-c,5,f,{textAlign:0,Of:0,Ve:2.5*b,sg:5.33*a});e=new C4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.t(g5,V4);g5.prototype.B=function(a){a=new d5(a,a.byteLength,this.A);if(XBa(a)){for(;a.o<a.A.byteLength;)for(0==a.version?a.C=f5(a)*(1E3/45):1==a.version&&(a.C=4294967296*f5(a)+f5(a)),a.F=e5(a);0<a.F;a.F--){var b=e5(a),c=e5(a),d=e5(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.C,type:this.track,Hy:c,Iy:d,order:b.o.length}))}JBa(this.o,a);return a.B}return[]};
g5.prototype.reset=function(){this.o.clear()};g.t(j5,V4);
j5.prototype.B=function(a,b){for(var c=[],d=a.split(rCa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!sCa.test(f)){var l=E5.exec(f);if(l&&4<=l.length){var m=k5(l[1]),n=k5(l[2])-m;m+=k;var p,r=p=void 0,v=void 0,D=void 0,H=l[3];l={textAlign:2};H=g.q(H?H.split(" "):[]);for(var L=H.next();!L.done;L=H.next())if(L=L.value.split(":"),2==L.length){var S=L[1];switch(L[0]){case "line":L=S.split(",");L[0].endsWith("%")&&(D=L[0],l.sg=Number.parseInt(D,10),2==L.length&&(v=L[1].trim()));break;case "position":L=S.split(",");
r=L[0];l.Ve=Number.parseInt(r,10);2==L.length&&(p=L[1].trim());break;case "align":switch(S){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}D||(l.sg=100,v||(v="end"));if(!r)switch(l.textAlign){case 0:l.Ve=0;break;case 1:l.Ve=100;break;default:l.Ve=50}r=0;switch(v){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Of=0>r||8<r?7:r;p=l;f=f.substring(E5.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=aCa(m,n,5,r),n=new C4(m,n,5,k.id,p,!1,g.Zb(f)?void 0:f),c.push(k),c.push(n),k.A.push(n);else for(v=p.split(tCa),1==v.length?(p=5,r=aCa(m,n,p,r)):(D=p=6,r=Object.assign({qs:32},r),r=new D4(m,n,D,"_"+E4++,r)),c.push(r),D=m,l=0;l<v.length;l++)H=v[l],0==l%2?(L=g.fs("<html>"+H+"</html>"),L.getElementsByTagName("parsererror").length?
(S=L.createElement("span"),S.appendChild(L.createTextNode(H))):S=L.firstChild,$Ba(this,D,n-(D-m),p,r,0<l,S,f,c)):D=k5(H)+k}E5.lastIndex=0}}return c};
var sCa=/^NOTE/,rCa=/(?:\r\n|\r|\n){2,}/,E5=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),tCa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(l5,g.M);l5.prototype.trackCount=function(){return h5(this.A,!0).length};
l5.prototype.Xd=function(){this.o=null};
l5.prototype.X=function(){g.M.prototype.X.call(this);this.Xd()};
l5.prototype.nE=function(){return!1};g.t(m5,l5);g.h=m5.prototype;g.h.ou=function(a,b){var c=this.Vl(a),d=(0,g.A)(function(c){this.B=null;b(c.responseText,a)},this);
this.Xd();this.B=g.xE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.pu=function(a,b,c,d){this.C=c;if(d)for(b=g.q(d.captionTracks),c=b.next();!c.done;c=b.next())i5(this.A,c.value);a()};
g.h.Vl=function(a){var b=a.Wa(),c={};if(this.C||a.B)c.fmt=this.C||"srv"+a.B;a.o&&(c.tlang=a.o.languageCode);return g.pE(b,c)};
g.h.Xd=function(){l5.prototype.Xd.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.Xd();l5.prototype.X.call(this)};n5.prototype.contains=function(a){a=g.db(this.ub,a);return 0<=a||0>a&&1==(-a-1)%2};
n5.prototype.length=function(){return this.ub.length/2};g.t(o5,g.M);g.h=o5.prototype;g.h.X=function(){g.M.prototype.X.call(this);this.B&&this.B.cancel()};
g.h.oC=function(a){var b=this;if(this.H.nk())var c=this.D.R(this.C,"progresssync",function(){b.H.index.Lb()&&(b.reset(),b.o=null,eCa(b,b.C.getCurrentTime()),b.D.Ha(c))});
else eCa(this,a)};
g.h.reset=function(){this.F=new n5;this.B&&(this.B.cancel(),this.B=null)};
g.h.jB=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Sg(a);!a||this.B||this.o&&30<this.o.startTime-this.C.getCurrentTime()||(a=this.o,a=a.o.uk(a),!g.Y(this.C).experiments.o("disable_captions_unknown_requests")&&!a.o[0].duration)||(this.F.contains(a.o[0].ya)||fCa(this,a),this.o=g.Ia(a.o));this.K.start()};
g.h.wU=function(a){var b=!(this.G?a.response:a.responseText)||400<=a.status;if(!g.Y(this.C).experiments.o("disable_captions_redirects_redux")){var c=g.jM(a);if(c){a=g.NL(this.A,this.L,{});b=this.A;g.JL(b.A,a,c);b.requestId=a.get("req_id");fCa(this,this.A);return}}b||null===this.J||(this.G?this.J(a.response,1E3*this.A.o[0].startTime,this.A.o[0].ya):this.J(a.responseText,1E3*this.A.o[0].startTime,this.A.o[0].ya));this.B=this.A=null};g.t(p5,l5);g.h=p5.prototype;g.h.ou=function(a,b){this.Xd();var c=gCa(this,a.A);if(c){var d=c.index.No(c.index.qf());g.Y(this.C).experiments.o("html5_disable_caption_starttime")||(d-=c.index.Ud(c.index.qf()));d*=1E3;var e=g.Y(this.C).Ma;this.D=new o5(new g.sL,this.C,c,function(c,e,l){b(c,a,e,d,l)},e||g.iI(c.info),(0,g.A)(function(){this.D&&this.D.reset();
this.o&&this.o.reset();this.F=!0},this))}};
g.h.nE=function(){var a=this.F;this.F=!1;return a};
g.h.pu=function(a){if(g.Y(this.C).Ma)i5(this.A,new g.VH({format:1,languageCode:"rawcc",languageName:"CC1",name:"",is_servable:!0,is_default:!0,is_translateable:!1})),i5(this.A,new g.VH({format:1,languageCode:"rawcc",languageName:"CC3",name:"",is_servable:!0,is_default:!0,is_translateable:!1}));else for(var b in this.B.o){var c=this.B.o[b];if(g.mI(c.info.mimeType)&&"rawcc"!=b&&("386"!=b||!g.Y(this.C).experiments.o("html5_manifestless_captions_fmt3_killswitch"))){var d="en",e="English",f=".en";if(c=
c.info.captionTrack)d=c.languageCode,e=c.displayName,f=c.vssId;i5(this.A,new g.VH({format:1,languageCode:d,languageName:e,name:"",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:f}))}}a()};
g.h.Xd=function(){l5.prototype.Xd.call(this);this.D&&(this.D.dispose(),this.D=null)};
g.h.Vl=function(){return""};
g.h.X=function(){this.Xd();l5.prototype.X.call(this)};g.t(r5,G4);r5.prototype.Tr=function(a){var b=this.H.A;G4.prototype.Tr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.A==e)var d=f;else{d={};g.Ga(d,c.A);g.Ga(d,uCa);var e=c.A;var f=d}DBa(this,c,d)}};
var uCa={Bt:!0};g.t(s5,G4);g.h=s5.prototype;g.h.GE=function(){g.ku(this.da)};
g.h.BU=function(){g.zq(this.element,"ytp-rollup-mode");this.nj(this.sa,!0)};
g.h.Tz=function(){return this.L};
g.h.Sz=function(){return this.H.params.yq*t5(this)};
g.h.nj=function(a,b){this.sa=a;if(t5(this)){for(var c=0,d=0;d<this.D.length&&c<a.length;d++)this.D[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.D.concat(a.slice(c)));c=this.L;this.L=0;G4.prototype.nj.call(this,a);d=this.C.offsetWidth+1;this.L=Math.max(hCa(this),c,d);c=this.H.params.yq*t5(this)-this.C.offsetHeight;c!=this.Z&&(b||(0,window.isNaN)(this.Z)||(g.T(this.element,"ytp-rollup-mode"),g.ju(this.da)),g.Ah(this.C,"transform",c?"translateY("+c+"px)":""),this.Z=c);G4.prototype.nj.call(this,a)}else G4.prototype.nj.call(this,
a)};g.t(u5,l5);g.h=u5.prototype;g.h.ou=function(a,b){var c=this.Vl(a),d=(0,g.A)(function(c){this.B=null;b(c.responseText,a)},this);
this.Xd();this.B=g.xE(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
g.h.pu=function(a,b,c){var d=this.D;b={type:"list",tlangs:1,v:this.C,fmts:Number(b||!1),vssids:1};this.QA&&(b.asrs=1);d=g.pE(d,b);b=(0,g.A)(function(b){this.B=null;if((b=b.responseXML)&&b.firstChild){for(var d=this.A,e=g.q(b.getElementsByTagName("track")),l=e.next();!l.done;l=e.next()){var m=l.value;l=m.getAttribute("formats");var n=m.getAttribute("lang_code"),p=m.getAttribute("lang_translated"),r=m.getAttribute("name"),v=m.getAttribute("kind"),D=m.getAttribute("id"),H="true"==m.getAttribute("lang_default"),
L="true"==m.getAttribute("cantran");m=m.getAttribute("vss_id");i5(d,new g.VH({formats:l,format:c,languageCode:n,languageName:p,name:r,kind:v,id:D,is_servable:!0,is_translateable:L,vss_id:m,is_default:H}))}b=b.getElementsByTagName("target");d=b.length;for(e=0;e<d;e++)l=b[e].getAttribute("lang_code"),n=b[e].getAttribute("lang_translated"),p=b[e].getAttribute("lang_original"),r=b[e].getAttribute("id"),v="true"==b[e].getAttribute("lang_default"),l={languageCode:l,languageName:n,languageOriginal:p,id:r,
is_default:v},this.F[l.languageCode]=l.languageName,this.G.push(new g.UH(l))}a()},this);
this.Xd();this.B=g.xE(d,{format:"RAW",onSuccess:b,withCredentials:!0})};
g.h.Vl=function(a){var b=this.D,c={v:this.C,type:"track",lang:a.A,name:a.F,kind:a.C,fmt:a.B};a.o&&(c.tlang=A4(a));return b=g.pE(b,c)};
g.h.Xd=function(){l5.prototype.Xd.call(this);this.B&&this.B.abort()};
g.h.X=function(){this.Xd();l5.prototype.X.call(this)};g.t(x5,g.JU);g.h=x5.prototype;g.h.X=function(){if(this.G){var a=g.DU(this.K);a&&a.Hj()}else nCa(this,!1);g.JU.prototype.X.call(this)};
g.h.KB=function(){return this.G?!this.B.Ca:this.ia||y5(this)?!0:iCa(this)};
g.h.load=function(a){g.JU.prototype.load.call(this);this.J=this.o.getAudioTrack();if(this.D||a)this.A&&(this.G&&!this.C.experiments.o("disable_native_caption_api")?jCa(this,!0):a?this.WD(a,this.A):3!=this.o.Ra()&&this.D.ou(this.A,(0,g.A)(this.WD,this))),this.A&&this.A!=z5(this)?this.o.xa("captionschanged",z4(this.A)):this.o.xa("onCaptionsTrackListChanged");else{var b;q5(this.B,this.K)?b=new p5(this.B.pa,this.o):this.B.captionTracks.length?b=new m5(this.B):b=new u5(this.B.co,this.B.videoId,this.B.lh||
this.C.lh||g.CP(this.B,"yt:cc_default_lang")||this.C.za,this.B.bo);this.D=b;b.pu((0,g.A)(this.eV,this),!0,this.G?"vtt":void 0,this.o.getAudioTrack())}};
g.h.unload=function(){this.G?this.C.experiments.o("disable_native_caption_api")?g.DU(this.K).Hj():this.A&&jCa(this,!1):(this.ha&&g.lu(this.ha),g.AU(this.o,"captions"),this.O=[],this.D&&this.D.Xd(),this.L&&g.xU(this.o,this.L),this.Aw());g.JU.prototype.unload.call(this);var a=g.iU(this.o.app);a&&a.F&&g.VP(a.F.B);this.o.xa("captionschanged",{})};
g.h.eV=function(){var a;this.M||iCa(this)?a=A5(this,this.M):y5(this)&&(a=z5(this));if(this.G||this.ia){for(var b=h5(this.D.A,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.WH(e),srclang:A4(e),id:e.toString()};this.ia||(f.src=this.D.Vl(e));e==a&&(f["default"]=1);c.push(g.K("TRACK",f))}g.DU(this.K).wl(c);(a=g.DU(this.K).na())&&a.textTracks&&a.textTracks.addEventListener&&!this.C.experiments.o("disable_native_caption_api")&&this.Y.R(a.textTracks,"change",this.fV)}else!this.A&&a&&
C5(this,a),this.o.xa("onCaptionsTrackListChanged"),this.o.xa("onApiChange")};
g.h.fV=function(){for(var a=g.DU(this.K).na().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=h5(this.D.A,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.A:null)!=b&&C5(this,b,!0)};
g.h.kX=function(){this.C.experiments.o("disable_native_caption_api")?this.loaded&&!this.G&&this.unload():!this.A&&this.G||this.unload()};
g.h.WD=function(a,b,c,d,e){a&&(this.D.nE()&&(this.O=[],g.AU(this.K,"captions"),this.da.Zj()),a=dCa(this.D,a,b,c,d),this.C.experiments.o("debug_web_player_live_captions_segment_numbers")&&c&&e&&(c=a.reduce(function(a,b){return b.start<a?b.start:a},Number.MAX_SAFE_INTEGER),b=a.reduce(function(a,b){return b.end>a?b.end:a},c)-c,d=new D4(c,b,0,"_"+E4++,{Of:2,
Ve:100,sg:0}),a.push(d),e=new C4(c,b,0,d.id,"sq="+e),a.push(e)),g.xU(this.o,a),this.M&&!this.ia&&kCa(this),this.M=!1)};
g.h.GN=function(a){this.O.push(a);this.da.Zj()};
g.h.HN=function(a){g.Ta(this.O,a);var b=q5(this.B,this.K)&&this.C.Ma;!this.C.experiments.o("disable_remove_displayed_close_caption_cue")&&b&&g.zU(this.o,[a]);this.da.Zj()};
g.h.ZV=function(a){if(a instanceof D4){var b=this.T[a.id];b&&b.H!=a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=lCa(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.ba[b]||(this.ba[b]=[]),this.ba[b].push(a)};
g.h.jW=function(){mCa(this,this.Z);this.Z=null};
g.h.QF=function(){this.da.stop();g.$b(this.ba);this.O.sort(g.VQ);var a=this.O;if(this.L){var b=(0,g.Pd)(a,function(a){return-1==this.L.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.ZV,this);g.Lb(this.T,function(a,b){this.ba[b]?(a.element.parentNode||g.CU(this.o,a.element,4),a.nj(this.ba[b])):(a.dispose(),delete this.T[b])},this)};
g.h.FE=function(){v5(this,{},!0)};
g.h.Vs=function(){var a=D5.ob;a={background:a.background,backgroundOpacity:a.nf,charEdgeStyle:a.wi,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.Oj,fontStyle:a.bold&&a.wf?3:a.bold?1:a.wf?2:0,textOpacity:a.ci,windowColor:D5.windowColor,windowOpacity:D5.ql};var b=w5(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.Dw=function(a,b){var c={};g.Ga(c,w5(this,"display-settings"));g.Ga(c,a);v5(this,c,b);this.o.V("captionssettingschanged")};
g.h.Aw=function(){!this.G&&this.loaded&&(g.Lb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.QF())};
g.h.Eu=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.gd(b,-2,4);this.Dw({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&C5(this,this.A,!0);break;case "stickyLoading":void 0!=b&&this.C.Fb&&B5(this,"module-enabled",!!b);break;case "track":if(!this.D)return{};if(b){if(this.G)break;if(!g.Ca(b))break;if(g.Zb(b)){C5(this,null,!0);break}var d;c=h5(this.D.A,!0);for(var e=0;e<c.length;e++){var f=c[e];f.A!=b.languageCode||d&&f.D!=b.languageName||(d=b.translationLanguage?
yBa(f,b.translationLanguage):f)}!d||d==this.A&&this.loaded||C5(this,d,!0)}else return this.loaded&&this.A&&this.A!=z5(this)?z4(this.A):{};return"";case "tracklist":return this.D?(0,g.I)(h5(this.D.A,!(!b||!b.includeAsr)),function(a){return z4(a)}):[];
case "translationLanguages":return this.D?this.D.G:[];case "displaySettings":d=this.Vs();if(g.sN(this.C)&&b&&g.Ca(b))if(b.reset)this.FE();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=oCa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=pCa(b[c],d[c]);break;case "charEdgeStyle":var k=g.r1[b[c]];f[c]=g.ta(k)?k:d[c];break;case "fontSizeIncrement":f[c]=qCa(b[c],d[c]);break;case "fontFamilyOption":k=g.q1[b[c]];f.fontFamily=
g.ta(k)?k:d[c];break;case "fontStyle":k=g.s1[b[c]],f[c]=g.ta(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.Dw(f,!0);d=this.Vs()}d.fontFamilyOption=g.gxa[d.fontFamily];d.charEdgeStyle=g.hxa[d.charEdgeStyle];d.fontStyle=g.ixa[d.fontStyle];return d;case "sampleSubtitles":this.G||void 0==b||nCa(this,!!b);break;case "xmlTrack":b&&this.C.Fb&&(this.G||C5(this,new g.VH({languageName:b.name}),!1,b.xml))}};
g.h.EN=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.C.Fb&&a.push("stickyLoading","xmlTrack");return a};
g.h.FN=function(){var a=this.A;return a?{cc:a.G}:{}};
g.h.GF=function(){this.loaded&&this.A&&this.A!=z5(this)?(B5(this,"module-enabled",!1),this.unload(),y5(this,!0)&&C5(this,z5(this),!1)):C5(this,this.A==z5(this)?A5(this,!0):this.A,!0)};
g.h.vR=function(){var a=this.A==z5(this);y5(this,a)?C5(this,this.o.getAudioTrack().Co,!1):this.B.captionTracks.length&&(this.loaded&&this.unload(),this.KB()&&(a?C5(this,A5(this),!1):this.load()))};g.AX.captions=x5;})(_yt_player);
