(function(g){var window=this;var vCa=function(a,b,c,d){var e=b.ac();g.U(a.element,"ytp-suggestion-set",!!e.videoId);var f=b.getPlaylistId();d=b.fd(c,d?d:"mqdefault.jpg");var k=b instanceof g.iP?g.aV(b.lengthSeconds):null,l=!!f;f=l&&"RD"==(new g.WQ(f.substr(0,2),f.substr(2))).type;var m=b instanceof g.iP?b.Ca:null;c={title:b.title,author:b.author,author_and_views:e.shortViewCount?b.author+" \u2022 "+e.shortViewCount:b.author,aria_label:b.xl||g.V("YTP_WATCH_VIDEO_OR_PLAYLIST",{TITLE:b.title},b.title),duration:k,url:b.Xl(c),is_live:m,
is_list:l,is_mix:f,background:d?"background-image: url("+d+")":""};b instanceof g.YQ&&(c.playlist_length=b.getLength());a.update(c)},F5=function(a,b){g.EH.call(this,{I:"div",
fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.A=a;this.created=!1},G5=function(a){g.W.call(this,{I:"div",
N:"ytp-upnext",U:{"aria-label":"{{aria_label}}"},P:[{I:"div",N:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{I:"span",N:"ytp-upnext-top",P:[{I:"span",N:"ytp-upnext-header",ca:"Neste"},{I:"span",N:"ytp-upnext-title",ca:"{{title}}"},{I:"span",N:"ytp-upnext-author",ca:"{{author}}"}]},{I:"a",N:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Spill av den neste videoen"},P:[{I:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},P:[{I:"circle",
N:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",N:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",N:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",N:"ytp-upnext-bottom",P:[{I:"span",N:"ytp-upnext-cancel"},{I:"span",N:"ytp-upnext-paused",ca:"Autoavspilling er satt p\u00e5 pause"}]}]});
this.D=null;var b=this.o["ytp-upnext-cancel"];this.D=new g.W({I:"button",fa:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Avbryt autoavspillingen"},ca:"Avbryt"});g.N(this,this.D);this.D.W("click",this.ER,this);this.D.wa(b);this.A=a;this.L=this.o["ytp-svg-autoplay-ring"];this.H=this.G=this.C=this.F=null;this.J=new g.iu(this.jo,5E3,this);g.N(this,this.J);this.K=0;this.R(this.o["ytp-upnext-autoplay-icon"],"click",this.PT);this.kD();this.R(a,"autonavvisibility",this.kD);this.R(a,
"mdxnowautoplaying",this.dT);this.R(a,"mdxautoplaycanceled",this.eT);this.R(a,"mdxautoplayupnext",this.TF);3==this.A.Ra()&&(a=(a=g.hU(g.cU(this.A)))?a.xK():null)&&this.TF(a)},wCa=function(a,b){a.F=b;
vCa(a,b,g.Y(a.A),"hqdefault.jpg")},H5=function(a,b){if(!a.C){g.fG("a11y-announce","Neste "+a.F.title);
a.K=g.qG();a.C=new g.iu((0,g.A)(a.Rr,a,b),25);a.Rr(b);var c=b||g.Y(a.A).experiments.A("autoplay_time")||1E4;a.A.xa("onAutonavCoundownStarted",c)}g.zq(a.element,"ytp-upnext-autoplay-paused")},J5=function(a){I5(a);
a.K=g.qG();a.Rr();g.T(a.element,"ytp-upnext-autoplay-paused")},I5=function(a){a.C&&(a.C.dispose(),a.C=null)},K5=function(a,b){b=void 0===b?!1:b;
var c=g.Y(a.A);if(c.experiments.o("autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var d=window.Notification.permission;"default"==d?window.Notification.requestPermission():"granted"!=d||window.document.hasFocus()||(d=a.F.ac(),a.jo(),a.G=new window.Notification("Neste",{body:d.title,icon:d.fd(c)}),a.H=a.R(a.G,"click",a.ET),a.J.start())}I5(a);a.A.Dk(!1,b)},xCa=function(a){F5.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.C=new g.W({I:"div",N:"ytp-subscribe-card",P:[{I:"img",N:"ytp-author-image",U:{src:b.profilePicture}},{I:"div",N:"ytp-subscribe-card-right",P:[{I:"div",N:"ytp-author-name",ca:b.author},{I:"div",N:"html5-subscribe-button-container"}]}]});g.N(this,this.C);this.C.wa(this.element);this.D=new g.RZ("Abonner",null,"Avslutt abonnementet",null,!0,!1,b.Kf,b.subscribed,"trailer-endscreen",null,null,a);g.N(this,this.D);this.D.wa(this.C.o["html5-subscribe-button-container"]);this.hide()},
L5=function(a){var b=g.Y(a),c=g.zJ||g.kf?{style:"will-change: opacity"}:void 0,d=b.o,e=["ytp-videowall-still"];
b.A&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",fa:e,U:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},P:[{I:"div",N:"ytp-videowall-still-image",U:{style:"{{background}}"}},{I:"span",N:"ytp-videowall-still-info",P:[{I:"span",N:"ytp-videowall-still-info-bg",P:[{I:"span",N:"ytp-videowall-still-info-content",U:c,P:[{I:"span",N:"ytp-videowall-still-info-title",ca:"{{title}}"},{I:"span",
N:"ytp-videowall-still-info-author",ca:"{{author_and_views}}"},{I:"span",N:"ytp-videowall-still-info-live",ca:"Direkte"},{I:"span",N:"ytp-videowall-still-info-duration",ca:"{{duration}}"}]}]}]},{I:"span",fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],P:[{I:"span",N:"ytp-videowall-still-listlabel-icon"},"Spilleliste",{I:"span",N:"ytp-videowall-still-listlabel-length",P:[" (",{I:"span",ca:"{{playlist_length}}"},")"]}]},{I:"span",fa:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],P:[{I:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"Samleliste",{I:"span",N:"ytp-videowall-still-listlabel-length",ca:" (50+)"}]}]});this.F=d;this.A=a;this.C=null;this.D=new g.OF(this);g.N(this,this.D);this.W("click",this.H);this.W("keypress",this.J);this.D.R(a,"videodatachange",this.G);g.Y(a).Z&&(a=a.app.ka,b=this.element,g.Oa(a.o,b),g.Ra(a.o,b),c=String(a.H++),b.setAttribute("data-visual-id",c),g.ef(this,(0,g.A)(a.G,a,b)));this.G()},M5=function(a){F5.call(this,
a,"videowall-endscreen");
this.M=a;this.H=0;this.D=[];this.J=this.G=this.F=null;this.K=this.T=!1;this.Y=new g.OF(this);g.N(this,this.Y);this.L=new g.iu(g.Fa(g.T,this.element,"ytp-show-tiles"),0);g.N(this,this.L);var b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Forrige"},P:[g.WU()]});g.N(this,b);b.wa(this.element);b.W("click",this.yP,this);this.O=new g.yH({I:"div",N:"ytp-endscreen-content"});g.N(this,this.O);this.O.wa(this.element);b=new g.W({I:"button",fa:["ytp-button","ytp-endscreen-next"],
U:{"aria-label":"Neste"},P:[g.XU()]});g.N(this,b);b.wa(this.element);b.W("click",this.xP,this);this.C=new G5(a);g.N(this,this.C);g.CU(this.A,this.C.element,4);this.hide()},N5=function(a){return g.EU(a.A)&&a.yy()&&!a.J},yCa=function(a,b){return(0,g.I)(b.suggestions,function(b){b=g.GX(b);
g.N(a,b);return b})},O5=function(a){var b=a.Zu();
b!=a.T&&(a.T=b,a.A.V("autonavvisibility"))},P5=function(a){g.JU.call(this,a);
this.A=null;this.B=new g.OF(this);g.N(this,this.B);this.C=g.Y(a);zCa(a)?this.A=new M5(this.o):this.C.Ga?this.A=new xCa(this.o):this.A=new F5(this.o);g.N(this,this.A);g.CU(this.o,this.A.element,4);this.EE();this.B.R(a,"videodatachange",this.EE,this);this.B.R(a,"crn_endscreen",this.wN,this);this.B.R(a,"crx_endscreen",this.xN,this)},zCa=function(a){a=g.Y(a);
return a.Ed&&!a.Ga};
g.t(F5,g.EH);F5.prototype.create=function(){this.created=!0};
F5.prototype.destroy=function(){this.created=!1};
F5.prototype.yy=function(){return!1};
F5.prototype.Zu=function(){return!1};g.t(G5,g.W);g.h=G5.prototype;g.h.jo=function(){this.G&&(this.J.stop(),this.Ha(this.H),this.H=null,this.G.close(),this.G=null)};
g.h.kD=function(){g.DH(this,g.dU(this.A))};
g.h.ET=function(){window.focus();this.jo()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Rr=function(a){a=a||g.Y(this.A).experiments.A("autoplay_time")||1E4;var b=Math.min(g.qG()-this.K,a);a=Math.min(b/a,1);this.L.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.A.Ra()?K5(this,!0):this.C&&this.C.start()};
g.h.PT=function(a){!g.Ud(this.D.element,g.CF(a))&&g.GW(a,this.A)&&K5(this)};
g.h.ER=function(){g.fU(this.A,!0)};
g.h.dT=function(a){this.A.Ra();this.show();H5(this,a)};
g.h.TF=function(a){this.A.Ra();this.F&&this.F.ac().videoId==a.ac().videoId||wCa(this,a)};
g.h.eT=function(){this.A.Ra();I5(this);this.hide()};
g.h.X=function(){I5(this);this.jo();g.W.prototype.X.call(this)};g.t(xCa,F5);g.t(L5,g.W);L5.prototype.Uk=function(){g.HU(this.A,this.element);var a=this.C.ac().videoId,b=this.C.getPlaylistId();g.a0(this.A.app,a,this.C.Vd,b,void 0,void 0,void 0)};
L5.prototype.H=function(a){g.GW(a,this.A,this.F,this.C.Vd||void 0)&&this.Uk()};
L5.prototype.J=function(a){switch(a.keyCode){case 13:case 32:g.HF(a)||(this.Uk(),g.GF(a))}};
L5.prototype.G=function(){var a=this.A.getVideoData(),b=g.Y(this.A);this.F=a.isDni?!1:b.o};g.t(M5,F5);g.h=M5.prototype;g.h.create=function(){F5.prototype.create.call(this);var a=this.A.getVideoData();a&&(this.F=yCa(this,a),this.G=a);this.Tg();this.Y.R(this.A,"appresize",this.Tg);this.Y.R(this.A,"onVideoAreaChange",this.Tg);this.Y.R(this.A,"videodatachange",this.zP);this.Y.R(this.A,"autonavchange",this.kC);this.Y.R(this.A,"autonavcancel",this.wP);this.Y.R(this.element,"transitionend",this.gV)};
g.h.destroy=function(){g.QF(this.Y);g.gf(this.D);this.D=[];this.F=null;F5.prototype.destroy.call(this);g.zq(this.element,"ytp-show-tiles");this.L.stop()};
g.h.yy=function(){return 1!=this.G.autonavState};
g.h.show=function(){F5.prototype.show.call(this);g.zq(this.element,"ytp-show-tiles");g.Y(this.A).A?g.ku(this.L):this.L.start();(this.K||this.J&&this.J!=this.G.clientPlaybackNonce)&&g.fU(this.A,!1);N5(this)?(O5(this),2==this.G.autonavState?g.Y(this.A).experiments.o("fast_autonav_in_background")&&3==this.A.bj()?K5(this.C,!0):H5(this.C):3==this.G.autonavState&&J5(this.C)):(g.fU(this.A,!0),O5(this))};
g.h.hide=function(){F5.prototype.hide.call(this);J5(this.C);O5(this)};
g.h.gV=function(a){g.CF(a)==this.element&&this.Tg()};
g.h.Tg=function(){if(this.F&&this.F.length){g.T(this.element,"ytp-endscreen-paginate");var a=g.uU(this.M,!0),b=g.SH(this.M);b&&(b=b.wd()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.F.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,v=b<=f-2&&n>=r*m,D=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&D)n-=p*m,e+=2;else if(v)n-=r*m,b+=2;else if(D)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.gd(a.width/m||1,1,1.21);n*=g.gd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Th(a,m,n);g.Ah(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});wCa(this.C,this.F[0]);g.U(this.element,"ytp-endscreen-takeover",N5(this));O5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&
2>f?0==k&&0==f&&(r=2):r=2),p=g.hd(p+this.H,l),0!=r){v=this.D[c];v||(v=new L5(this.A),this.D[c]=v,a.appendChild(v.element));D=Math.floor(n*k/e);var H=Math.floor(m*f/b),L=Math.floor(n*(k+r)/e)-D-4,S=Math.floor(m*(f+r)/b)-H-4;g.Hh(v.element,H,D);g.Th(v.element,S,L);g.Ah(v.element,"transitionDelay",(k+f)/20+"s");g.U(v.element,"ytp-videowall-still-mini",1==r);g.U(v.element,"ytp-videowall-still-large",2<r);r=v;p=this.F[p];r.C!=p&&(r.C=p,vCa(r,p,g.Y(r.A),g.xq(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":
"mqdefault.jpg"),v=(p=p.Vd)&&p.itct)&&(p=r.A,g.Y(p).Z&&(p=p.app.ka,r=r.element,D=r.getAttribute("data-visual-id"),g.Oa(p.o,r),g.FU(p,"onLogServerVeCreated",{id:D,tracking_params:v})));c++}g.U(this.element,"ytp-endscreen-paginate",c<l);for(b=this.D.length-1;b>=c;b--)e=this.D[b],g.Od(e.element),g.ff(e);this.D.length=c}};
g.h.zP=function(){var a=this.A.getVideoData();this.G!=a&&(this.H=0,this.F=yCa(this,a),this.G=a,this.Tg())};
g.h.xP=function(){this.H+=this.D.length;this.Tg()};
g.h.yP=function(){this.H-=this.D.length;this.Tg()};
g.h.BM=function(){return!!this.C.C};
g.h.kC=function(a){1==a?(this.K=!1,this.J=this.G.clientPlaybackNonce,I5(this.C),this.B&&this.Tg()):(this.K=!0,this.B&&N5(this)&&(2==a?H5(this.C):3==a&&J5(this.C)))};
g.h.wP=function(a){if(a){for(a=0;a<this.D.length;a++)g.IU(this.M,this.D[a].element,!0);this.kC(1)}else this.J=null,this.K=!1;this.Tg()};
g.h.Zu=function(){return this.B&&N5(this)};g.t(P5,g.JU);g.h=P5.prototype;g.h.JB=function(){var a=this.o.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!zCa(this.o)||b;a=g.GP(a,"ypc_module");var c=g.b0(this.o.app);return b&&!a&&!c};
g.h.IB=function(){return this.A.Zu()};
g.h.xM=function(){return this.IB()?this.A.BM():!1};
g.h.X=function(){g.AU(this.o,"endscreen");g.JU.prototype.X.call(this)};
g.h.load=function(){g.JU.prototype.load.call(this);this.A.show()};
g.h.unload=function(){g.JU.prototype.unload.call(this);this.A.hide();this.A.destroy()};
g.h.wN=function(a){this.JB()&&(this.A.created||this.A.create(),"load"==a.getId()&&this.load())};
g.h.xN=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.EE=function(){g.AU(this.o,"endscreen");var a=Math.max(1E3*(this.o.getVideoData().lengthSeconds-10),0);a=new g.UQ(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.N(this,a);var b=new g.UQ(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.N(this,b);g.xU(this.o,[a,b])};g.AX.endscreen=P5;})(_yt_player);
