(function(g){var window=this;var bDa=function(a,b){return g.Wb(a,b)},p6=function(a){g.Om(a,"zx",g.yb());
return a},q6=function(a,b,c){g.za(c)||(c=[String(c)]);
g.Rm(a.o,b,c)},cDa=function(a,b){var c=[];
g.Dk(b,function(a){try{var b=g.nD.prototype.A.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.u(b)?g.mD(b)&&c.push(a):c.push(a)},a);
return c},dDa=function(a,b){var c=cDa(a,b);
(0,g.C)(c,function(a){g.nD.prototype.remove.call(this,a)},a)},eDa=function(a){if(a.Dd){if(a.Dd.locationOverrideToken)return{locationOverrideToken:a.Dd.locationOverrideToken};
if(null!=a.Dd.latitudeE7&&null!=a.Dd.longitudeE7)return{latitudeE7:a.Dd.latitudeE7,longitudeE7:a.Dd.longitudeE7}}return null},fDa=function(a,b,c,d){var e=new g.Fm(null,void 0);
a&&g.Gm(e,a);b&&g.Hm(e,b);c&&g.Im(e,c);d&&g.Jm(e,d);return e},gDa=function(a){g.bG[a]&&(a=g.bG[a],(0,g.C)(a,function(a){g.$F[a]&&delete g.$F[a]}),a.length=0)},hDa=function(a){var b=g.ZF();
if(b)if(b.clear(a),a)gDa(a);else for(var c in g.bG)gDa(c)},r6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.zm;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",iDa(this,a.capabilities||""),jDa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",
this.o=a.localChannelEncryptionKey||"")},iDa=function(a,b){a.capabilities.clear();
(0,g.Pd)(b.split(","),g.Fa(bDa,kDa)).forEach(function(b){a.capabilities.add(b)})},jDa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},s6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},t6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},lDa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},mDa=function(a){return new s6(a)},nDa=function(a){return g.za(a)?(0,g.I)(a,mDa):[]},u6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},v6=function(a){return g.za(a)?"["+(0,g.I)(a,u6).join(",")+"]":"null"},w6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},oDa=function(a){return(0,g.I)(a,function(a){return{key:a.id,
name:a.name}})},x6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},y6=function(a,b){return g.Ka(a,function(a){return t6(a,b)})},pDa=function(){var a=(0,g.YG)();
a&&dDa(a,a.o.Zd(!0))},z6=function(){var a=g.aH("yt-remote-connected-devices")||[];
g.fb(a);return a},qDa=function(a){if(g.Pa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.I)(a,function(a,b){return 0==b?a:a.substring(c.length)})},rDa=function(a){g.$G("yt-remote-connected-devices",a,86400)},B6=function(){if(A6)return A6;
var a=g.aH("yt-remote-device-id");a||(a=w6(),g.$G("yt-remote-device-id",a,31536E3));for(var b=z6(),c=1,d=a;g.Oa(b,d);)c++,d=a+"#"+c;return A6=d},C6=function(){var a=z6(),b=B6();
g.Oa(a,b);g.cH()&&g.ib(a,b);a=qDa(a);if(g.Pa(a))try{g.KG("remote_sid")}catch(c){}else try{g.JG("remote_sid",a.join(","),-1)}catch(c){}},sDa=function(){return g.aH("yt-remote-session-browser-channel")},tDa=function(){return g.aH("yt-remote-local-screens")||[]},uDa=function(){g.$G("yt-remote-lounge-token-expiration",!0,86400)},vDa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.I)(tDa(),function(a){return a.loungeToken}),c=(0,g.I)(a,function(a){return a.loungeToken});
(0,g.nm)(c,function(a){return!g.Oa(b,a)})&&uDa();
g.$G("yt-remote-local-screens",a,31536E3)},wDa=function(a,b){g.$G("yt-remote-session-browser-channel",a);
g.$G("yt-remote-session-screen-id",b);var c=z6(),d=B6();g.Oa(c,d)||c.push(d);rDa(c);C6()},D6=function(a){a||(g.bH("yt-remote-session-screen-id"),g.bH("yt-remote-session-video-id"));
C6();a=z6();g.Ta(a,B6());rDa(a)},xDa=function(){if(!E6){var a=g.yD();
a&&(E6=new g.hD(a))}return E6?!!E6.get("yt-remote-use-staging-server"):!1},yDa=function(){var a=window.document.createElement("a");
g.dd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},zDa=function(a,b){var c=g.Hd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.ed(c,g.fe("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},ADa=function(){var a=yDa(),b=window.document.getElementById(a),c=b&&g.kF(b,"loaded");
c||b&&!c||(b=zDa(a,function(){g.kF(b,"loaded")||(g.jF(b,"loaded","true"),g.fG(a),g.gE(g.Fa(hDa,a),0))}))},F6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},BDa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},G6=function(a){a.length?CDa(a.shift(),function(){G6(a)}):H6()},DDa=function(a){return"chrome-extension://"+a+I6},CDa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},J6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},H6=function(){var a=BDa();
a&&a(!1,"No cast extension found")},K6=function(){if(EDa){var a=2,b=BDa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;CDa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",H6,c)}},FDa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(K6(),a({command:"cast.sender.init"}))},GDa=function(){K6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);G6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+I6,"//www.gstatic.com/eureka/clank"+I6])},L6=function(a,b,c){g.M.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.ud=b;this.D=(0,g.A)(this.DK,this);this.o=!1;this.A=0;this.B=this.Fa=null;this.C=[]},M6=function(){},N6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.Vm(this);this.A=new g.Bg;this.A.setInterval(250)},IDa=function(a,b,c){a.ck=1;
a.zh=p6(b.clone());a.ij=c;a.D=!0;HDa(a,null)},O6=function(a,b,c,d,e){a.ck=1;
a.zh=p6(b.clone());a.ij=null;a.D=c;e&&(a.OE=!1);HDa(a,d)},HDa=function(a,b){a.Tk=(0,g.G)();
P6(a);a.Zh=a.zh.clone();q6(a.Zh,"t",a.F);a.tn=0;a.Rc=a.o.As(a.o.cn()?b:null);0<a.lt&&(a.oq=new g.gl((0,g.A)(a.eG,a,a.Rc),a.lt));a.Y.W(a.Rc,"readystatechange",a.bW);var c=a.Gi?g.ec(a.Gi):{};a.ij?(a.gr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Zh,a.gr,a.ij,c)):(a.gr="GET",a.OE&&!g.Dd&&(c.Connection="close"),a.Rc.send(a.Zh,a.gr,null,c));a.o.Cf(1)},LDa=function(a,b,c){for(var d=!0;!a.ri&&a.tn<c.length;){var e=JDa(a,c);
if(e==Q6){4==b&&(a.Ah=4,R6(15),d=!1);break}else if(e==KDa){a.Ah=4;R6(16);d=!1;break}else S6(a,e)}4==b&&0==c.length&&(a.Ah=1,R6(17),d=!1);a.If=a.If&&d;d||(T6(a),U6(a))},JDa=function(a,b){var c=a.tn,d=b.indexOf("\n",c);
if(-1==d)return Q6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return KDa;d+=1;if(d+c>b.length)return Q6;var e=b.substr(d,c);a.tn=d+c;return e},NDa=function(a,b){a.Tk=(0,g.G)();
P6(a);var c=b?window.location.hostname:"";a.Zh=a.zh.clone();g.Om(a.Zh,"DOMAIN",c);g.Om(a.Zh,"t",a.F);try{a.Jf=new window.ActiveXObject("htmlfile")}catch(n){T6(a);a.Ah=7;R6(22);U6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in V6)k=V6[l];else if(l in MDa)k=V6[l]=MDa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=V6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.fd(g.yc("b/12014412"),d);a.Jf.open();a.Jf.write(g.Wc(c));a.Jf.close();a.Jf.parentWindow.m=(0,g.A)(a.jV,a);a.Jf.parentWindow.d=(0,g.A)(a.XD,a,!0);a.Jf.parentWindow.rpcClose=(0,g.A)(a.XD,a,!1);c=a.Jf.createElement("DIV");a.Jf.parentWindow.document.body.appendChild(c);d=g.Nc(a.Zh.toString());d=g.rb(g.Kc(d));d=g.fd(g.yc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Wc(d);
a.o.Cf(1)},P6=function(a){a.Qw=(0,g.G)()+a.C;
ODa(a,a.C)},ODa=function(a,b){if(null!=a.pl)throw Error("WatchDog timer not null");
a.pl=W6((0,g.A)(a.zV,a),b)},X6=function(a){a.pl&&(g.x.clearTimeout(a.pl),a.pl=null)},U6=function(a){a.o.gA()||a.ri||a.o.Zp(a)},T6=function(a){X6(a);
g.ff(a.oq);a.oq=null;a.A.stop();g.an(a.Y);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.Jf&&(a.Jf=null)},S6=function(a,b){try{a.o.PD(a,b),a.o.Cf(4)}catch(c){}},QDa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;PDa(a,b,function(e){e?c(!0):g.x.setTimeout(function(){QDa(a,b,c,d,f)},f)})}},PDa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{Y6(d),c(!0)}catch(e){}};
d.onerror=function(){try{Y6(d),c(!1)}catch(e){}};
d.onabort=function(){try{Y6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{Y6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},Y6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},RDa=function(a){this.o=a;
this.A=new M6},SDa=function(a){var b=Z6(a.o,a.Al,"/mail/images/cleardot.gif");
p6(b);QDa(b.toString(),5E3,(0,g.A)(a.JJ,a),3,2E3);a.Cf(1)},a7=function(a){var b=a.o.J;
if(null!=b)R6(5),b?(R6(11),$6(a.o,a,!1)):(R6(12),$6(a.o,a,!0));else if(a.Be=new N6(a,void 0,void 0,void 0),a.Be.Gi=a.jt,b=a.o,b=Z6(b,b.cn()?a.dm:null,a.kt),R6(5),!g.Bd||g.uc(10))q6(b,"TYPE","xmlhttp"),O6(a.Be,b,!1,a.dm,!1);else{q6(b,"TYPE","html");var c=a.Be;a=!!a.dm;c.ck=3;c.zh=p6(b.clone());NDa(c,a)}},b7=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new M6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},TDa=function(a,b){this.o=a;
this.map=b;this.context=null},UDa=function(a){g.hf.call(this,"statevent",a)},VDa=function(a,b){g.hf.call(this,"timingevent",a);
this.size=b},WDa=function(a){g.hf.call(this,"serverreachability",a)},ZDa=function(a){XDa(a);
if(3==a.o){var b=a.Mm++,c=a.Do.clone();g.Om(c,"SID",a.B);g.Om(c,"RID",b);g.Om(c,"TYPE","terminate");c7(a,c);b=new N6(a,a.B,b,void 0);b.ck=2;b.zh=p6(c.clone());(new window.Image).src=b.zh;b.Tk=(0,g.G)();P6(b)}YDa(a)},$Da=function(a){a.eK(1,0);
a.Do=Z6(a,null,a.it);d7(a)},XDa=function(a){a.nh&&(a.nh.abort(),a.nh=null);
a.wc&&(a.wc.cancel(),a.wc=null);a.Ag&&(g.x.clearTimeout(a.Ag),a.Ag=null);e7(a);a.fe&&(a.fe.cancel(),a.fe=null);a.rh&&(g.x.clearTimeout(a.rh),a.rh=null)},aEa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new TDa(a.WQ++,b));2!=a.o&&3!=a.o||d7(a)},d7=function(a){a.fe||a.rh||(a.rh=W6((0,g.A)(a.VD,a),0),a.Qj=0)},cEa=function(a,b){if(1==a.o){if(!b){a.Mm=Math.floor(1E5*Math.random());
var c=a.Mm++,d=new N6(a,"",c,void 0);d.Gi=null;var e=f7(a),f=a.Do.clone();g.Om(f,"RID",c);g.Om(f,"CVER","1");c7(a,f);IDa(d,f,e);a.fe=d;a.o=2}}else 3==a.o&&(b?bEa(a,b):0==a.A.length||a.fe||bEa(a))},bEa=function(a,b){if(b)if(6<a.ti){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.Mm-1;var d=f7(a)}else c=b.G,d=b.ij;else c=a.Mm++,d=f7(a);var e=a.Do.clone();g.Om(e,"SID",a.B);g.Om(e,"RID",c);g.Om(e,"AID",a.rk);c7(a,e);c=new N6(a,a.B,c,a.Qj+1);c.Gi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.fe=c;IDa(c,e,d)},c7=function(a,b){if(a.td){var c=a.td.Nz();
c&&g.Lb(c,function(a,c){g.Om(b,c,a)})}},f7=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.ti&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.ti?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},dEa=function(a){a.wc||a.Ag||(a.G=1,a.Ag=W6((0,g.A)(a.UD,a),0),a.Dj=0)},g7=function(a){if(a.wc||a.Ag||3<=a.Dj)return!1;
a.G++;a.Ag=W6((0,g.A)(a.UD,a),eEa(a,a.Dj));a.Dj++;return!0},$6=function(a,b,c){a.fr=c;
a.Yf=b.Mg;a.F||$Da(a)},e7=function(a){null!=a.xi&&(g.x.clearTimeout(a.xi),a.xi=null)},eEa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},h7=function(a,b){if(2==b||9==b){var c=null;
a.td&&(c=null);var d=(0,g.A)(a.WW,a);c||(c=new g.Fm("//www.google.com/images/cleardot.gif"),p6(c));PDa(c.toString(),1E4,d)}else R6(2);fEa(a,b)},fEa=function(a,b){a.o=0;
a.td&&a.td.Jy(b);YDa(a);XDa(a)},YDa=function(a){a.o=0;
a.Yf=-1;if(a.td)if(0==a.C.length&&0==a.A.length)a.td.ks();else{g.Wa(a.C);var b=g.Wa(a.A);a.C.length=0;a.A.length=0;a.td.ks(b)}},Z6=function(a,b,c){var d=g.Pm(c);
if(""!=d.A)b&&g.Hm(d,b+"."+d.A),g.Im(d,d.D);else{var e=window.location;d=fDa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Ml&&g.Lb(a.Ml,function(a,b){g.Om(d,b,a)});
g.Om(d,"VER",a.ti);c7(a,d);return d},W6=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},R6=function(a){i7.dispatchEvent(new UDa(i7,a))},gEa=function(){},hEa=function(a,b){this.action=a;
this.params=b||{}},j7=function(a,b){g.M.call(this);
this.o=new g.iu(this.aV,0,this);g.N(this,this.o);this.ud=5E3;this.A=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},k7=function(a,b,c){this.L=a;
this.F=b;this.B=new g.gD;this.A=new j7(this.GX,this);this.o=this.bb=null;this.K=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.M=c||!1},iEa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.fr,sessionId:a.o.B,arrayId:a.o.rk}},jEa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&cEa(a.o),ZDa(a.o));a.H=0},l7=function(a){return!!a.o&&3==a.o.o},kEa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},m7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||window.document.location.href;var b=g.Rg(a)||"";b&&(this.port=":"+b);this.domain=g.Qg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.A=!1))},n7=function(a,b){var c=a.o;
if(g.u(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.bh(c+b,{})},o7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Fa(a.C,d,!0),onError:g.Fa(a.B,e),Ad:g.Fa(a.D,e)};c&&(a.Pb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xE(b,a)},oEa=function(){var a=lEa;
mEa();p7.push(a);nEa(p7)},q7=function(a,b){mEa();
var c=p7,d=pEa(a,String(b));g.Pa(c)?qEa(d):(nEa(c),(0,g.C)(c,function(a){a(d)}))},mEa=function(){p7||(p7=g.y("yt.mdx.remote.debug.handlers_")||[],g.ua("yt.mdx.remote.debug.handlers_",p7,void 0))},qEa=function(a){var b=(r7+1)%50;
r7=b;s7[b]=a;t7||(t7=49==b)},nEa=function(a){var b=s7;
if(b[0]){var c=r7,d=t7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
s7=Array(50);r7=-1;t7=!1}},pEa=function(a,b){var c=((0,g.G)()-rEa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},u7=function(a){g.RF.call(this);
this.G=a;this.o=[]},sEa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},tEa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.Pd)(a.o,function(a){return!!x6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=sEa(a,b[d])||c;return c},uEa=function(a,b){var c=a.o.length;
a.o=(0,g.Pd)(a.o,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.o.length<c},v7=function(a,b,c,d){g.RF.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Fa=window.NaN},x7=function(a){u7.call(this,"LocalScreenService");
this.B=a;this.A=window.NaN;w7(this);this.info("Initializing with "+v6(this.o))},vEa=function(a){if(a.o.length){var b=(0,g.I)(a.o,function(a){return a.id}),c=n7(a.B,"/pairing/get_lounge_token_batch");
o7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.QK,a),(0,g.A)(a.PK,a))}},w7=function(a){var b=nDa(tDa());
b=(0,g.Pd)(b,function(a){return!a.uuid});
return tEa(a,b)},y7=function(a,b){vDa((0,g.I)(a.o,lDa));
b&&uDa()},A7=function(a,b){g.RF.call(this);
this.F=b;var c=g.aH("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Oa(c,l)}this.o=d;this.D=a;this.B=this.C=window.NaN;this.A=null;z7("Initialized with "+g.Ig(this.o))},wEa=function(a,b,c){var d=n7(a.D,"/pairing/get_screen_availability");
o7(a.D,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},B7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.o))var c=!1;
else{c=g.Tb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(z7("Updated online screens: "+g.Ig(a.o)),a.o=b,a.V("screenChange"));xEa(a)},C7=function(a){(0,window.isNaN)(a.B)||g.iE(a.B);
a.B=g.gE((0,g.A)(a.aw,a),0<a.C&&a.C<(0,g.G)()?2E4:1E4)},z7=function(a){q7("OnlineScreenService",a)},yEa=function(a){var b={};
(0,g.C)(a.F(),function(a){a.token?b[a.token]=a.id:this.hc("Requesting availability of screen w/o lounge token.")});
return b},xEa=function(a){a=g.Tb(g.Mb(a.o,function(a){return a}));
g.fb(a);a.length?g.$G("yt-remote-online-screen-ids",a.join(","),60):g.bH("yt-remote-online-screen-ids")},D7=function(a){u7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};zEa(this)},BEa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.te();if(k=(c?y6(k,c):null)||y6(k,b)){k.uuid=b;var l=E7(a,k);wEa(a.A,l,function(a){e(a?l:null)})}else c?AEa(a,c,(0,g.A)(function(a){var f=E7(this,new s6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));wEa(this.A,f,function(a){e(a?f:null)})},a),f):e(null)},CEa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},AEa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Pb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.xE(n7(a.F,"/pairing/get_lounge_token_batch"),e)},DEa=function(a){a.o=a.B.te();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+v6(a.o))},zEa=function(a){F7(a);
a.B=new x7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.fL,a));DEa(a);a.C=nDa(g.aH("yt-remote-automatic-screen-cache")||[]);F7(a);a.info("Initializing automatic screens: "+v6(a.C));a.A=new A7(a.F,(0,g.A)(a.te,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},E7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=y6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.$G("yt-remote-automatic-screen-cache",(0,g.I)(a.C,lDa)));F7(a);a.D[b.uuid]=b.id;g.$G("yt-remote-device-id-map",a.D,31536E3);return b},F7=function(a){a.D=g.aH("yt-remote-device-id-map")||{}},G7=function(a,b,c){g.RF.call(this);
this.M=c;this.J=a;this.A=b;this.B=null},H7=function(a,b){q7(a.M,b)},I7=function(a,b){G7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.MX,this);this.D=(0,g.A)(this.MV,this);this.C=g.gE((0,g.A)(function(){EEa(this,null)},this),12E4)},FEa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ig(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){H7(this,"Failed to send message: getMdxSessionStatus.")},a)):H7(a,"Sending yt message without session: "+g.Ig(b))},EEa=function(a,b){g.iE(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.aq,a),d=(0,g.A)(a.ze,a);a.Yz(b,c,d,5)}}else a.ze(Error("Waiting for session status timed out."))},J7=function(a,b,c){G7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.O=c;this.D=null;this.G=g.z;this.F=window.NaN;this.L=(0,g.A)(this.PX,this);this.o=g.z},GEa=function(a){a.o=a.J.lG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(a){this.o=g.z;
this.aq(a)},a),(0,g.A)(function(a){this.o=g.z;
this.ze(a)},a))},HEa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.O;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}xDa()&&(b.env_useStageMdx=1);return g.$g(b)},K7=function(a,b){G7.call(this,a,b,"ManualSession");
this.o=g.gE((0,g.A)(this.tk,this,null),150)},L7=function(a,b,c,d){g.RF.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.nU,this)},IEa=function(a,b){return b?g.Ka(a.B,function(a){return t6(b,a.label)},a):null},M7=function(a){q7("Controller",a)},lEa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},N7=function(a){return a.D||!!a.B.length||!!a.o},O7=function(a,b,c){b!=a.o&&(g.ff(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.SD,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.tk(null)):a.V("yt-remote-cast2-session-change",null))},JEa=function(a){var b=a.A.kG(),c=a.o&&a.o.A;
a=(0,g.I)(b,function(a){c&&t6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=IEa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},PEa=function(a,b,c,d,e,f,k){KEa()?LEa(b,e,f,k)&&(Q7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?MEa(a,c):(window.__onGCastApiAvailable=function(b,d){b?MEa(a,c):(R7("Failed to load cast API: "+d),S7(!1),Q7(!1),g.bH("yt-remote-cast-available"),g.bH("yt-remote-cast-receiver"),NEa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):ADa():J6("CriOS")?FDa():J6("Android")&&J6("Chrome/")&&window.navigator.presentation?GDa():window.chrome&&window.navigator.presentation&&!J6("Edge")?(K6(),G6(OEa.map(DDa))):H6())):P7("Cannot initialize because not running Chrome")},NEa=function(){P7("dispose");
var a=T7();a&&a.dispose();g.ua("yt.mdx.remote.cloudview.instance_",null,void 0);QEa(!1);g.dG(U7);U7.length=0},V7=function(){return!!g.aH("yt-remote-cast-installed")},REa=function(){var a=g.aH("yt-remote-cast-receiver");
return a?a.friendlyName:null},SEa=function(){P7("clearCurrentReceiver");
g.bH("yt-remote-cast-receiver")},TEa=function(){return V7()?T7()?T7().getCastSession():(R7("getCastSelector: Cast is not initialized."),null):(R7("getCastSelector: Cast API is not installed!"),null)},X7=function(){V7()?T7()?W7()?(P7("Requesting cast selector."),T7().requestSession()):(P7("Wait for cast API to be ready to request the session."),U7.push(g.cG("yt-remote-cast2-api-ready",X7))):R7("requestCastSelector: Cast is not initialized."):R7("requestCastSelector: Cast API is not installed!")},Y7=
function(a,b){W7()?T7().setConnectedScreenStatus(a,b):R7("setConnectedScreenStatus called before ready.")},KEa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.zJ||a},UEa=function(a,b){T7().init(a,b)},LEa=function(a,b,c,d){var e=!1;
T7()||(a=new L7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.$G("yt-remote-cast-available",a);g.gG("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){P7("onReceiverSelected: "+a.friendlyName);
g.$G("yt-remote-cast-receiver",a);g.gG("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){P7("onReceiverResumed: "+a.friendlyName);
g.$G("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){P7("onSessionChange: "+u6(a));
a||g.bH("yt-remote-cast-receiver");g.gG("yt-remote-cast2-session-change",a)}),g.ua("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
P7("cloudview.createSingleton_: "+e);return e},T7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},MEa=function(a,b){S7(!0);
Q7(!1);UEa(a,function(a){a?(QEa(!0),g.fG("yt-remote-cast2-api-ready")):(R7("Failed to initialize cast API."),S7(!1),g.bH("yt-remote-cast-available"),g.bH("yt-remote-cast-receiver"),NEa());b(a)})},P7=function(a){q7("cloudview",a)},R7=function(a){q7("cloudview",a)},S7=function(a){P7("setCastInstalled_ "+a);
g.$G("yt-remote-cast-installed",a)},W7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},QEa=function(a){P7("setApiReady_ "+a);
g.ua("yt.mdx.remote.cloudview.apiReady_",a,void 0)},Q7=function(a){g.ua("yt.mdx.remote.cloudview.initializing_",a,void 0)},Z7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.o=-1;this.muted=!1;this.audioTrackId=null;this.G=this.H=0;this.A=null;this.hasNext=this.dg=!1;this.K=this.J=this.B=this.D=0;this.C=window.NaN;this.F=!1;this.reset(a)},$7=function(a){a.audioTrackId=null;
a.A=null;a.o=-1;a.dg=!1;a.hasNext=!1;a.H=0;a.G=(0,g.G)();a.D=0;a.B=0;a.J=0;a.K=0;a.C=window.NaN;a.F=!1},a8=function(a){return a.qb()?((0,g.G)()-a.G)/1E3:0},b8=function(a,b){a.H=b;
a.G=(0,g.G)()},c8=function(a){switch(a.o){case 1:case 1081:return((0,g.G)()-a.G)/1E3+a.H;
case -1E3:return 0}return a.H},d8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&$7(a)},e8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.o;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.fc(a.A);b.hasPrevious=a.dg;b.hasNext=a.hasNext;b.playerTime=a.H;b.playerTimeAt=a.G;b.seekableStart=a.D;b.seekableEnd=a.B;b.duration=a.J;b.loadedTime=a.K;b.liveIngestionTime=a.C;return b},g8=function(a,b){g.RF.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.xC;this.B=this.A=null;this.J=(0,g.A)(this.HR,this);this.G=(0,g.A)(this.Pm,this);this.H=(0,g.A)(this.GR,this);this.K=(0,g.A)(this.TR,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Xw,this),VEa(this))):c=3;0!=c&&(b?this.Xw(c):g.gE((0,g.A)(function(){this.Xw(c)},this),0));
var d=TEa();d&&f8(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},h8=function(a){return new Z7(a.C.getPlayerContextData())},VEa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.F.push(this.C.subscribe(a,g.Fa(this.iU,a),this))},a)},WEa=function(a){(0,g.C)(a.F,function(a){this.C.unsubscribeByKey(a)},a);
a.F.length=0},i8=function(a,b){50>a.D.xc()&&g.zC(a.D,b)},k8=function(a,b,c){var d=h8(a);
b8(d,c);-1E3!=d.o&&(d.o=b);j8(a,d)},l8=function(a,b,c){a.C.sendMessage(b,c)},j8=function(a,b){WEa(a);
a.C.setPlayerContextData(e8(b));VEa(a)},f8=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.Pm(null));
a.B=b;a.B&&(q7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.Pm(a.B.media[0]))},XEa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=h8(a);b.contentId!=d.videoId&&q7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.o=c.playerState;b8(d,a.A.getEstimatedTime());j8(a,d)}else q7("CP","No cast media video. Ignoring state update.")},m8=function(a,b,c){return(0,g.A)(function(a){this.hc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.hc("Retrying "+b+" using MDx browser channel."),l8(this,b,c))},a)},n8=function(a,b,c){g.RF.call(this);
this.D=window.NaN;this.O=!1;this.K=this.J=this.L=this.M=window.NaN;this.T=[];this.C=this.G=this.B=this.fb=this.o=null;this.sa=a;this.T.push(g.AF(window,"beforeunload",(0,g.A)(this.HK,this)));this.A=[];this.fb=new Z7;this.ba=b.id;this.o=YEa(this,c);this.o.subscribe("handlerOpened",this.LR,this);this.o.subscribe("handlerClosed",this.IR,this);this.o.subscribe("handlerError",this.JR,this);this.o.subscribe("handlerMessage",this.KR,this);kEa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.fb.videoId;g.cH()&&g.$G("yt-remote-session-video-id",a)},this)},o8=function(a){q7("conn",a)},YEa=function(a,b){return new k7(n7(a.sa,"/bc"),b)},p8=function(a,b){a.V("proxyStateChange",b)},ZEa=function(a){a.D=g.gE((0,g.A)(function(){o8("Connecting timeout");
this.F(1)},a),2E4)},q8=function(a){g.iE(a.D);
a.D=window.NaN},r8=function(a){g.iE(a.M);
a.M=window.NaN},$Ea=function(a){s8(a);
a.L=g.gE((0,g.A)(function(){t8(this,"getNowPlaying")},a),2E4)},s8=function(a){g.iE(a.L);
a.L=window.NaN},bFa=function(a,b){b&&(q8(a),r8(a));
b==(l7(a.o)&&(0,window.isNaN)(a.D))?b&&(p8(a,1),t8(a,"getSubtitlesTrack")):b?(a.Z()&&a.fb.reset(),p8(a,1),t8(a,"getNowPlaying"),aFa(a)):a.F(1)},cFa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.fb.videoId&&(g.Zb(b.params)?a.fb.A=null:a.fb.A=b.params,a.V("remotePlayerChange"))},dFa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.fb.listId=b.params.listId||a.fb.listId;d8(a.fb,c,d);a.V("remoteQueueChange")},fFa=function(a,b){b.params=b.params||{};
dFa(a,b);eFa(a,b);a.V("autoplayDismissed")},eFa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
b8(a.fb,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.fb.o&&(c=-1E3);a.fb.o=c;c=Number(b.params.loadedTime);a.fb.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.fb.J=(0,window.isNaN)(c)?0:c;c=a.fb;var d=Number(b.params.liveIngestionTime);c.C=d;c.F=(0,window.isNaN)(d)?!1:!0;c=a.fb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.D=(0,window.isNaN)(d)?0:d;c.B=(0,window.isNaN)(e)?0:e;1==a.fb.o?$Ea(a):s8(a);
a.V("remotePlayerChange")},gFa=function(a,b){if(-1E3!=a.fb.o){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.fb.o=c;c=(0,window.parseInt)(b.params.currentTime,10);b8(a.fb,(0,window.isNaN)(c)?0:c);a.V("remotePlayerChange")}},hFa=function(a,b){var c="true"==b.params.muted;
a.fb.volume=(0,window.parseInt)(b.params.volume,10);a.fb.muted=c;a.V("remotePlayerChange")},iFa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},jFa=function(a,b){var c="true"==b.params.hasNext;
a.fb.dg="true"==b.params.hasPrevious;a.fb.hasNext=c;a.V("previousNextChange")},aFa=function(a){g.iE(a.K);
a.K=g.gE((0,g.A)(a.F,a,1),864E5)},t8=function(a,b,c){c?o8("Sending: action="+b+", params="+g.Ig(c)):o8("Sending: action="+b);
a.o.sendMessage(b,c)},u8=function(a){u7.call(this,"ScreenServiceProxy");
this.hd=a;this.A=[];this.A.push(this.hd.$_s("screenChange",(0,g.A)(this.KX,this)));this.A.push(this.hd.$_s("onlineScreenChange",(0,g.A)(this.HT,this)))},oFa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.aE("MDX_CONFIG")||b;pDa();C6();v8||(v8=new m7(b?b.loungeApiHost:void 0),xDa()&&(v8.o="/api/loungedev"));w8||(w8=g.y("yt.mdx.remote.deferredProxies_")||[],g.ua("yt.mdx.remote.deferredProxies_",w8,void 0));kFa();var c=x8();if(!c){var d=new D7(v8);g.ua("yt.mdx.remote.screenService_",d,void 0);c=x8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);PEa(a,d,function(a){a?y8()&&Y7(y8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.gG("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.ua("yt.mdx.remote.initialized_",!0,void 0),z8("Initializing: "+g.Ig(b)),A8.push(g.cG("yt-remote-cast2-availability-change",function(){g.gG("yt-remote-receiver-availability-change")})),A8.push(g.cG("yt-remote-cast2-receiver-selected",function(){B8(null);
g.gG("yt-remote-auto-connect","cast-selector-receiver")})),A8.push(g.cG("yt-remote-cast2-receiver-resumed",function(){g.gG("yt-remote-receiver-resumed","cast-selector-receiver")})),A8.push(g.cG("yt-remote-cast2-session-change",lFa)),A8.push(g.cG("yt-remote-connection-change",function(a){a?Y7(y8(),"YouTube TV"):C8()||(Y7(null,null),SEa())})),a=D8(),b.isAuto&&(a.id+="#dial"),g.XF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),z8(" -- with channel params: "+
g.Ig(a)),mFa(a),c.start(),y8()||nFa())},qFa=function(){var a=pFa();
V7()&&g.aH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},pFa=function(){var a=x8().hd.$_gos();
var b=E8();b&&F8()&&(x6(a,b)||a.push(b));return oDa(a)},G8=function(){var a=rFa();
!a&&V7()&&REa()&&(a={key:"cast-selector-receiver",name:REa()});return a},rFa=function(){var a=pFa(),b=E8();
b||(b=C8());return g.Ka(a,function(a){return b&&t6(b,a.key)?!0:!1})},E8=function(){var a=y8();
if(!a)return null;var b=x8().te();return y6(b,a)},lFa=function(a){z8("remote.onCastSessionChange_: "+u6(a));
if(a){var b=E8();b&&b.id==a.id?Y7(b.id,"YouTube TV"):(b&&H8(),I8(a,1))}else F8()&&H8()},H8=function(){W7()?T7().stopSession():R7("stopSession called before API ready.");
var a=F8();a&&(a.disconnect(1),J8(null))},K8=function(){var a=F8();
return!!a&&3!=a.getProxyState()},z8=function(a){q7("remote",a)},x8=function(){if(!L8){var a=g.y("yt.mdx.remote.screenService_");
L8=a?new u8(a):null}return L8},y8=function(){return g.y("yt.mdx.remote.currentScreenId_")},sFa=function(a){g.ua("yt.mdx.remote.currentScreenId_",a,void 0)},tFa=function(){return g.y("yt.mdx.remote.connectData_")},B8=function(a){g.ua("yt.mdx.remote.connectData_",a,void 0)},F8=function(){return g.y("yt.mdx.remote.connection_")},J8=function(a){var b=F8();
B8(null);a||sFa("");g.ua("yt.mdx.remote.connection_",a,void 0);w8&&((0,g.C)(w8,function(b){b(a)}),w8.length=0);
b&&!a?g.gG("yt-remote-connection-change",!1):!b&&a&&g.gG("yt-remote-connection-change",!0)},C8=function(){var a=g.cH();
if(!a)return null;var b=x8().te();return y6(b,a)},I8=function(a,b){E8()&&E8();
sFa(a.id);var c=new n8(v8,a,D8());c.connect(b,tFa());c.subscribe("beforeDisconnect",function(a){g.gG("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){F8()&&J8(null)});
J8(c)},nFa=function(){var a=C8();
a?(z8("Resume connection to: "+u6(a)),I8(a,0)):(D6(),SEa(),z8("Skipping connecting because no session screen found."))},kFa=function(){var a=D8();
if(g.Zb(a)){a=B6();var b=g.aH("yt-remote-session-name")||"",c=g.aH("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.ua("yt.mdx.remote.channelParams_",a,void 0)}},D8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},mFa=function(a){a?(g.$G("yt-remote-session-app",a.app),g.$G("yt-remote-session-name",a.name)):(g.bH("yt-remote-session-app"),g.bH("yt-remote-session-name"));
g.ua("yt.mdx.remote.channelParams_",a,void 0)},M8=function(a,b,c){g.M.call(this);
this.H=a;this.A=b;this.B=new g.OF(this);g.N(this,this.B);this.B.R(b,"onCaptionsTrackListChanged",this.aT);this.B.R(b,"captionschanged",this.FR);this.B.R(b,"captionssettingschanged",this.yF);this.B.R(b,"videoplayerreset",this.bq);this.B.R(b,"mdxautoplaycancel",this.IJ);this.T=this.B.R(b,"onVolumeChange",this.BD);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.OD,this);c.subscribe("remotePlayerChange",this.Sm,this);c.subscribe("remoteQueueChange",this.bq,this);c.subscribe("autoplayUpNext",this.mD,
this);c.subscribe("previousNextChange",this.LD,this);c.subscribe("nowAutoplaying",this.DD,this);c.subscribe("autoplayDismissed",this.lD,this);this.suggestion=null;this.J=new g.pQ(64);this.C=new g.iu(this.uF,500,this);g.N(this,this.C);this.D=new g.iu(this.vF,1E3,this);g.N(this,this.D);this.L=new L6(this.lX,0,this);g.N(this,this.L);this.F={};this.M=new g.iu(this.UF,1E3,this);g.N(this,this.M);this.K=new g.gl(this.DP,1E3,this);g.N(this,this.K);this.O=g.z;this.yF();this.bq();this.Sm()},N8=function(a,b){var c=
a.H,d=a.A.getVideoData().lengthSeconds;
c.J=b||0;c.o.V("progresssync",b,d)},uFa=function(a){N8(a,0);
a.C.stop();O8(a,new g.pQ(64))},Q8=function(a,b){if(P8(a)&&!a.G){var c=null;
b&&(c={style:a.A.aj()},g.hc(c,b));a.o.iF(a.A.getVideoData(1).videoId,c);a.F=h8(a.o).A}},R8=function(a,b){var c=a.A.kg();
if(c){var d=c.re();var e=c.listId.toString()}var f=a.A.getVideoData(1);c=a.o;var k=f.videoId,l=d;d=f.playerParams;var m=f.lk;f=eDa(f);var n=h8(c);l=l||0;var p={videoId:k,currentIndex:l};d8(n,k,l);g.u(b)&&(b8(n,b),p.currentTime=b);g.u(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.Ig(f));l8(c,"setPlaylist",p);e||j8(c,n);O8(a,new g.pQ(1))},vFa=function(a,b){if(b){var c=a.A.Ac("captions","tracklist",{QA:1});
c&&c.length?(a.A.Td("captions","track",b),a.G=!1):(a.A.Ck("captions"),a.G=!0)}else a.A.Td("captions","track",{})},P8=function(a){return h8(a.o).videoId==a.A.getVideoData(1).videoId},O8=function(a,b){a.D.stop();
var c=a.J;if(!g.uQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.mU(a.A,d);a.J=b;wFa(a.H,c,b)}},S8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.Xqa()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.A=new g.cV(this,250);g.N(this,this.A);this.C=a;this.R(a,"presentingplayerstatechange",this.D);xFa(this,g.jU(a))},xFa=function(a,b){if(3==a.C.Ra()){var c={RECEIVER_NAME:a.C.Ac("remote","currentReceiver").name};
c=g.X(b,128)?g.h0("Feil p\u00e5 $RECEIVER_NAME",c):b.qb()||g.X(b,4)?g.h0("Spilles av p\u00e5 $RECEIVER_NAME",c):g.h0("Koblet til $RECEIVER_NAME",c);a.updateValue("statustext",c);a.A.show()}else a.A.hide()},T8=function(a,b){g.nZ.call(this,"Spill av p\u00e5",0,a,b);
this.A=a;this.J={};this.R(a,"onMdxReceiversChange",this.L);this.R(a,"presentingplayerstatechange",this.L);this.L()},U8=function(a){g.JU.call(this,a);
this.B={key:w6(),name:"Denne datamaskinen"};this.D=null;this.F=[];this.K=this.A=null;this.H=[this.B];this.C=this.B;this.G=new g.pQ(64);this.J=0;if(!g.zN(g.Y(this.o))){a=this.o;var b=g.SH(a);b&&(b=b.yp())&&(b=new T8(a,b),g.N(this,b));b=new S8(a);g.N(this,b);g.CU(a,b.element,4)}},wFa=function(a,b,c){a.G=c;
a.o.V("presentingplayerstatechange",new g.zQ(c,b))},V8=function(a,b){if(b.key!=a.C.key)if(b.key==a.B.key)H8();
else{a.C=b;var c=a.o.getPlaylistId();var d=a.o.getVideoData(1);var e=d.videoId;if(c||e){var f=a.o.kg();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.ac(l).videoId}else k=[e];f=a.o.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.lk,index:Math.max(a.o.TB(),0),currentTime:0==f?void 0:f};(d=eDa(d))&&(c.locationInfo=d);d=c}else d=null;z8("Connecting to: "+g.Ig(b));"cast-selector-receiver"==b.key?(B8(d||null),W7()?T7().setLaunchParams(d||null):
R7("setLaunchParams called before ready.")):!d&&K8()&&y8()==b.key?g.gG("yt-remote-connection-change",!0):(H8(),B8(d||null),d=x8().te(),(d=y6(d,b.key))&&I8(d,1))}},MDa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},V6={"'":"\\'"},yFa={},kDa={aZ:"atp",E3:"ska",T2:"que",d2:"mus",A3:"sus",j0:"dsp"};
r6.prototype.no=function(){var a=new r6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var E6,A6="",I6=F6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",EDa=F6("loadCastFramework")||F6("loadCastApplicationFramework"),OEa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(L6,g.M);g.h=L6.prototype;g.h.CK=function(a){this.C=arguments;this.o=!1;this.Fa?this.B=(0,g.G)()+this.ud:this.Fa=g.Cg(this.D,this.ud)};
g.h.stop=function(){this.Fa&&(g.Dg(this.Fa),this.Fa=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.X=function(){this.stop();L6.ea.X.call(this)};
g.h.DK=function(){this.B?(this.Fa=g.Cg(this.D,this.B-(0,g.G)()),this.B=null):(this.Fa=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};M6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
M6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=N6.prototype;g.h.Gi=null;g.h.If=!1;g.h.pl=null;g.h.Qw=null;g.h.Tk=null;g.h.ck=null;g.h.zh=null;g.h.Zh=null;g.h.ij=null;g.h.Rc=null;g.h.tn=0;g.h.Jf=null;g.h.gr=null;g.h.Ah=null;g.h.fm=-1;g.h.OE=!0;g.h.ri=!1;g.h.lt=0;g.h.oq=null;var KDa={},Q6={};g.h=N6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.bW=function(a){a=a.target;var b=this.oq;b&&3==g.tx(a)?b.ak():this.eG(a)};
g.h.eG=function(a){try{if(a==this.Rc)a:{var b=g.tx(this.Rc),c=this.Rc.A,d=this.Rc.getStatus();if(g.Bd&&!g.uc(10)||g.Dd&&!g.tc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.kf&&!g.xx(this.Rc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.Cf(3):this.o.Cf(2));X6(this);var e=this.Rc.getStatus();this.fm=e;var f=g.xx(this.Rc);(this.If=200==e)?(4==b&&T6(this),this.D?(LDa(this,b,f),g.kf&&this.If&&3==b&&(this.Y.W(this.A,"tick",this.XV),this.A.start())):S6(this,f),this.If&&!this.ri&&(4==b?this.o.Zp(this):
(this.If=!1,P6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ah=3,R6(13)):(this.Ah=0,R6(14)),T6(this),U6(this))}}catch(k){this.Rc&&g.xx(this.Rc)}finally{}};
g.h.XV=function(){var a=g.tx(this.Rc),b=g.xx(this.Rc);this.tn<b.length&&(X6(this),LDa(this,a,b),this.If&&4!=a&&P6(this))};
g.h.jV=function(a){W6((0,g.A)(this.iV,this,a),0)};
g.h.iV=function(a){this.ri||(X6(this),S6(this,a),P6(this))};
g.h.XD=function(a){W6((0,g.A)(this.hV,this,a),0)};
g.h.hV=function(a){this.ri||(T6(this),this.If=a,this.o.Zp(this),this.o.Cf(4))};
g.h.cancel=function(){this.ri=!0;T6(this)};
g.h.zV=function(){this.pl=null;var a=(0,g.G)();0<=a-this.Qw?(2!=this.ck&&this.o.Cf(3),T6(this),this.Ah=2,R6(18),U6(this)):ODa(this,this.Qw-a)};g.h=RDa.prototype;g.h.jt=null;g.h.Be=null;g.h.pq=!1;g.h.hA=null;g.h.zo=null;g.h.ku=null;g.h.kt=null;g.h.Se=null;g.h.Mg=-1;g.h.dm=null;g.h.Al=null;g.h.connect=function(a){this.kt=a;a=Z6(this.o,null,this.kt);R6(3);this.hA=(0,g.G)();var b=this.o.H;null!=b?(this.dm=b[0],(this.Al=b[1])?(this.Se=1,SDa(this)):(this.Se=2,a7(this))):(q6(a,"MODE","init"),this.Be=new N6(this,void 0,void 0,void 0),this.Be.Gi=this.jt,O6(this.Be,a,!1,null,!0),this.Se=0)};
g.h.JJ=function(a){if(a)this.Se=2,a7(this);else{R6(4);var b=this.o;b.Yf=b.nh.Mg;h7(b,9)}a&&this.Cf(2)};
g.h.As=function(a){return this.o.As(a)};
g.h.abort=function(){this.Be&&(this.Be.cancel(),this.Be=null);this.Mg=-1};
g.h.gA=function(){return!1};
g.h.PD=function(a,b){this.Mg=a.fm;if(0==this.Se)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Yf=this.Mg;h7(c,2);return}this.dm=c[0];this.Al=c[1]}else c=this.o,c.Yf=this.Mg,h7(c,2);else if(2==this.Se)if(this.pq)R6(7),this.ku=(0,g.G)();else if("11111"==b){if(R6(6),this.pq=!0,this.zo=(0,g.G)(),c=this.zo-this.hA,!g.Bd||g.uc(10)||500>c)this.Mg=200,this.Be.cancel(),R6(12),$6(this.o,this,!0)}else R6(8),this.zo=this.ku=(0,g.G)(),this.pq=!1};
g.h.Zp=function(){this.Mg=this.Be.fm;if(this.Be.If)0==this.Se?this.Al?(this.Se=1,SDa(this)):(this.Se=2,a7(this)):2==this.Se&&((!g.Bd||g.uc(10)?!this.pq:200>this.ku-this.zo)?(R6(11),$6(this.o,this,!1)):(R6(12),$6(this.o,this,!0)));else{0==this.Se?R6(9):2==this.Se&&R6(10);var a=this.o;a.Yf=this.Mg;h7(a,2)}};
g.h.cn=function(){return this.o.cn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Cf=function(a){this.o.Cf(a)};g.h=b7.prototype;g.h.Ml=null;g.h.fe=null;g.h.wc=null;g.h.it=null;g.h.Do=null;g.h.zy=null;g.h.Ro=null;g.h.Mm=0;g.h.WQ=0;g.h.td=null;g.h.rh=null;g.h.Ag=null;g.h.xi=null;g.h.nh=null;g.h.fr=null;g.h.rk=-1;g.h.eB=-1;g.h.Yf=-1;g.h.Qj=0;g.h.Dj=0;g.h.ti=8;var i7=new g.Lf;g.B(UDa,g.hf);g.B(VDa,g.hf);g.B(WDa,g.hf);g.h=b7.prototype;g.h.connect=function(a,b,c,d,e){R6(0);this.it=b;this.Ml=c||{};d&&g.u(e)&&(this.Ml.OSID=d,this.Ml.OAID=e);this.F?(W6((0,g.A)(this.Uy,this,a),100),$Da(this)):this.Uy(a)};
g.h.Uy=function(a){this.nh=new RDa(this);this.nh.jt=null;this.nh.A=this.D;this.nh.connect(a)};
g.h.gA=function(){return 0==this.o};
g.h.VD=function(a){this.rh=null;cEa(this,a)};
g.h.UD=function(){this.Ag=null;this.wc=new N6(this,this.B,"rpc",this.G);this.wc.Gi=null;this.wc.lt=0;var a=this.zy.clone();g.Om(a,"RID","rpc");g.Om(a,"SID",this.B);g.Om(a,"CI",this.fr?"0":"1");g.Om(a,"AID",this.rk);c7(this,a);if(!g.Bd||g.uc(10))g.Om(a,"TYPE","xmlhttp"),O6(this.wc,a,!0,this.Ro,!1);else{g.Om(a,"TYPE","html");var b=this.wc,c=!!this.Ro;b.ck=3;b.zh=p6(a.clone());NDa(b,c)}};
g.h.PD=function(a,b){if(0!=this.o&&(this.wc==a||this.fe==a))if(this.Yf=a.fm,this.fe==a&&3==this.o)if(7<this.ti){try{var c=this.D.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Ag){if(this.wc)if(this.wc.Tk+3E3<this.fe.Tk)e7(this),this.wc.cancel(),this.wc=null;else break a;g7(this);R6(19)}}else this.eB=c[1],0<this.eB-this.rk&&37500>c[2]&&this.fr&&0==this.Dj&&!this.xi&&(this.xi=W6((0,g.A)(this.zR,this),6E3));else h7(this,11)}else b!=yFa.d_.o&&h7(this,11);else if(this.wc==a&&
e7(this),!g.E(b)){c=this.D.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.rk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Ro=e[2],e=e[3],null!=e?this.ti=e:this.ti=6,this.o=3,this.td&&this.td.Ly(),this.zy=Z6(this,this.cn()?this.Ro:null,this.it),dEa(this)):"stop"==e[0]&&h7(this,7):3==this.o&&("stop"==e[0]?h7(this,7):"noop"!=e[0]&&this.td&&this.td.Ky(e),this.Dj=0)}}};
g.h.zR=function(){null!=this.xi&&(this.xi=null,this.wc.cancel(),this.wc=null,g7(this),R6(20))};
g.h.Zp=function(a){if(this.wc==a){e7(this);this.wc=null;var b=2}else if(this.fe==a)this.fe=null,b=1;else return;this.Yf=a.fm;if(0!=this.o)if(a.If)1==b?(b=(0,g.G)()-a.Tk,i7.dispatchEvent(new VDa(i7,a.ij?a.ij.length:0,b,this.Qj)),d7(this),this.C.length=0):dEa(this);else{var c=a.Ah,d;if(!(d=3==c||7==c||0==c&&0<this.Yf)){if(d=1==b)this.fe||this.rh||1==this.o||2<=this.Qj?d=!1:(this.rh=W6((0,g.A)(this.VD,this,a),eEa(this,this.Qj)),this.Qj++,d=!0);d=!(d||2==b&&g7(this))}if(d)switch(c){case 1:h7(this,5);
break;case 4:h7(this,10);break;case 3:h7(this,6);break;case 7:h7(this,12);break;default:h7(this,2)}}};
g.h.eK=function(a){if(!g.Oa(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.WW=function(a){a?R6(2):(R6(1),fEa(this,8))};
g.h.As=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.nx;a.H=!1;return a};
g.h.isActive=function(){return!!this.td&&this.td.isActive(this)};
g.h.Cf=function(a){i7.dispatchEvent(new WDa(i7,a))};
g.h.cn=function(){return!(!g.Bd||g.uc(10))};
g.h=gEa.prototype;g.h.Ly=function(){};
g.h.Ky=function(){};
g.h.Jy=function(){};
g.h.ks=function(){};
g.h.Nz=function(){return{}};
g.h.isActive=function(){return!0};g.B(j7,g.M);g.h=j7.prototype;g.h.aV=function(){this.ud=Math.min(3E5,2*this.ud);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.ud+15E3*Math.random();g.ju(this.o,a);this.A=(0,g.G)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.ud=5E3};g.B(k7,gEa);g.h=k7.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Yd=function(a){return this.B.Yd(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.ff(this.B),jEa(this),g.ff(this.A),this.A=null)};
g.h.ma=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new b7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.o;e&&(e.td=null);d.td=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.rk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.hc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):l7(this)&&aEa(this.o,c)};
g.h.Ly=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)aEa(this.o,a[b])}this.V("handlerOpened")};
g.h.Jy=function(a){var b=2==a&&401==this.o.Yf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.ks=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.Nz=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.hc(a,this.D);return a};
g.h.Ky=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),ZDa(this.o)):this.V("handlerMessage",new hEa(a[0],a[1]))};
g.h.GX=function(){this.A.isActive();var a=this.o,b=0;a.wc&&b++;a.fe&&b++;0!=b||this.connect(this.D,this.C)};m7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
m7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
m7.prototype.D=function(a){a(Error("request timed out"))};var rEa=(0,g.G)(),p7=null,s7=Array(50),r7=-1,t7=!1;g.B(u7,g.RF);u7.prototype.te=function(){return this.o};
u7.prototype.contains=function(a){return!!x6(this.o,a)};
u7.prototype.get=function(a){return a?y6(this.o,a):null};
u7.prototype.info=function(a){q7(this.G,a)};g.B(v7,g.RF);var zFa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=v7.prototype;g.h.start=function(){!this.o&&(0,window.isNaN)(this.Fa)&&this.jG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);(0,window.isNaN)(this.Fa)||(g.iE(this.Fa),this.Fa=window.NaN)};
g.h.X=function(){this.stop();v7.ea.X.call(this)};
g.h.jG=function(){this.Fa=window.NaN;this.o=g.xE(n7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.IX,this),onError:(0,g.A)(this.HX,this),Ad:(0,g.A)(this.JX,this)})};
g.h.IX=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new s6(c))};
g.h.HX=function(a){this.o=null;a.status&&404==a.status?this.A>=zFa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=zFa[this.A],this.Fa=g.gE((0,g.A)(this.jG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.JX=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(x7,u7);g.h=x7.prototype;g.h.start=function(){w7(this)&&this.V("screenChange");!g.aH("yt-remote-lounge-token-expiration")&&vEa(this);g.iE(this.A);this.A=g.gE((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){w7(this);sEa(this,a);y7(this,!1);this.V("screenChange");b(a);a.token||vEa(this)};
g.h.remove=function(a,b){var c=w7(this);uEa(this,a)&&(y7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.Wq=function(a,b,c,d){var e=w7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,y7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.X=function(){g.iE(this.A);x7.ea.X.call(this)};
g.h.QK=function(a){w7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}y7(this,!b);b&&q7(this.G,"Missed "+b+" lounge tokens.")};
g.h.PK=function(a){q7(this.G,"Requesting lounge tokens failed: "+a)};g.B(A7,g.RF);g.h=A7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.aH("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.G)()-144E5<a?0:a)?C7(this):(this.C=(0,g.G)()+3E5,g.$G("yt-remote-fast-check-period",this.C),this.aw())};
g.h.isEmpty=function(){return g.Zb(this.o)};
g.h.update=function(){z7("Updating availability on schedule.");var a=this.F(),b=g.Mb(this.o,function(b,d){return b&&!!y6(a,d)},this);
B7(this,b)};
g.h.X=function(){g.iE(this.B);this.B=window.NaN;this.A&&(this.A.abort(),this.A=null);A7.ea.X.call(this)};
g.h.aw=function(){g.iE(this.B);this.B=window.NaN;this.A&&this.A.abort();var a=yEa(this);if(g.Pb(a)){var b=n7(this.D,"/pairing/get_screen_availability");this.A=o7(this.D,b,{lounge_token:g.Tb(a).join(",")},(0,g.A)(this.IU,this,a),(0,g.A)(this.HU,this))}else B7(this,{}),C7(this)};
g.h.IU=function(a,b){this.A=null;var c=g.Tb(yEa(this));if(g.gb(c,g.Tb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;B7(this,d);C7(this)}else this.hc("Changing Screen set during request."),this.aw()};
g.h.HU=function(a){this.hc("Screen availability failed: "+a);this.A=null;C7(this)};
g.h.hc=function(a){q7("OnlineScreenService",a)};g.B(D7,u7);g.h=D7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.Wq=function(a,b,c,d){this.B.contains(a)?this.B.Wq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,q7(this.G,a),d(Error(a)))};
g.h.te=function(a){return a?this.o:g.Va(this.o,(0,g.Pd)(this.C,function(a){return!this.contains(a)},this))};
g.h.kG=function(){return(0,g.Pd)(this.te(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.lG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new v7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.ff(f);d(E7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.ff(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.LX=function(a,b,c,d){g.xE(n7(this.F,"/pairing/get_screen"),{method:"POST",Pb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(a,d){var e=new s6(d.screen||{});if(!e.name||CEa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);CEa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(E7(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Ad:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.X=function(){g.ff(this.B);g.ff(this.A);D7.ea.X.call(this)};
g.h.fL=function(){DEa(this);this.V("screenChange");this.A.update()};
D7.prototype.dispose=D7.prototype.dispose;g.B(G7,g.RF);g.h=G7.prototype;g.h.aq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.ze=function(a){this.ma()||(a&&H7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){q7(this.M,a)};
g.h.nG=function(){return null};
g.h.hw=function(a){var b=this.A;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){H7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.X=function(){this.hw("");G7.ea.X.call(this)};g.B(I7,G7);g.h=I7.prototype;g.h.gw=function(a){if(this.o){if(this.o==a)return;H7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);FEa(this)};
g.h.tk=function(a){this.info("launchWithParams no-op for Cast: "+g.Ig(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.ze()},this),(0,g.A)(function(){this.ze(Error("Failed to stop receiver app."))},this)):this.ze(Error("Stopping cast device witout session."))};
g.h.hw=g.z;g.h.X=function(){this.info("disposeInternal");g.iE(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;I7.ea.X.call(this)};
g.h.MV=function(a,b){if(!this.ma())if(b){var c=g.hx(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ig(c));switch(d){case "mdxSessionStatus":EEa(this,c.screenId);break;default:H7(this,"Unknown youtube message: "+d)}}else H7(this,"Unable to parse message.")}else H7(this,"No data in message.")};
g.h.Yz=function(a,b,c,d){BEa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(H7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.gE((0,g.A)(this.Yz,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.nG=function(){return this.o};
g.h.MX=function(a){this.ma()||a||(H7(this,"Cast session died."),this.ze())};g.B(J7,G7);g.h=J7.prototype;g.h.gw=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.tk=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.iE(this.F);this.C?this.C.stop((0,g.A)(this.ze,this,null),(0,g.A)(this.ze,this,"Failed to stop DIAL device.")):this.ze()};
g.h.X=function(){this.o();this.o=g.z;g.iE(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;J7.ea.X.call(this)};
g.h.PX=function(a){this.ma()||a||(H7(this,"DIAL session died."),this.o(),this.o=g.z,this.ze())};
g.h.Yt=function(a){this.K=w6();if(this.D){var b=new window.chrome.cast.DialLaunchResponse(!0,HEa(this));a(b);GEa(this)}else this.G=(0,g.A)(function(){g.iE(this.F);this.G=g.z;this.F=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,HEa(this));a(b);GEa(this)},this),this.F=g.gE((0,g.A)(function(){this.G()},this),100)};
g.h.uM=function(a,b,c){BEa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(a){a&&a.token?(this.aq(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.Yt(b,c)},this),(0,g.A)(function(a){H7(this,"Failed to get DIAL screen: "+a);
this.Yt(b,c)},this))};g.B(K7,G7);K7.prototype.stop=function(){this.ze()};
K7.prototype.gw=g.z;K7.prototype.tk=function(){g.iE(this.o);this.o=window.NaN;var a=y6(this.J.te(),this.A.label);a?this.aq(a):this.ze(Error("No such screen"))};
K7.prototype.X=function(){g.iE(this.o);this.o=window.NaN;K7.ea.X.call(this)};g.B(L7,g.RF);g.h=L7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.RD,this),(0,g.A)(this.rU,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.kS,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ma()||(window.chrome.cast.addReceiverActionListener(this.C),oEa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.mG,this)),this.B=JEa(this),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Ig(a))},this)),this.V("yt-remote-cast2-availability-change",N7(this)),b(!0))},this),(0,g.A)(function(a){this.hc("Failed to initialize API: "+g.Ig(a));
b(!1)},this))};
g.h.DW=function(a,b){M7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)M7("Unsetting old screen status: "+this.o.A.friendlyName),O7(this,null)}if(a&&b){if(!this.o){c=y6(this.A.te(),a);if(!c){M7("setConnectedScreenStatus: Unknown screen.");return}var d=IEa(this,c);d||(M7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.B.push(d),
window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(a){this.hc("Failed to set initial custom receivers: "+g.Ig(a))},this)));
M7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);O7(this,new K7(this.A,d),!0)}this.o.hw(b)}else M7("setConnectedScreenStatus: no screen.")};
g.h.EW=function(a){this.ma()?this.hc("Setting connection data on disposed cast v2"):this.o?this.o.tk(a):this.hc("Setting connection data without a session")};
g.h.OX=function(){this.ma()?this.hc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),O7(this,null)):M7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.RD,this),(0,g.A)(this.MU,this))};
g.h.X=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.mG,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.C);g.Ta(g.y("yt.mdx.remote.debug.handlers_")||[],lEa);g.ff(this.o);L7.ea.X.call(this)};
g.h.hc=function(a){q7("Controller",a)};
g.h.SD=function(a,b){this.o==a&&(b||O7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.nU=function(a,b){if(!this.ma())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),M7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)M7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{M7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:O7(this,
new K7(this.A,a));break;case window.chrome.cast.ReceiverType.DIAL:O7(this,new J7(this.A,a,this.F));break;case window.chrome.cast.ReceiverType.CAST:O7(this,new I7(this.A,a));break;default:this.hc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.hc("Stopping receiver w/o session: "+a.friendlyName)}else this.hc("onReceiverAction_ called without receiver.")};
g.h.kS=function(a){if(this.ma())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.hc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.hc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.o.B)return M7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.hc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);O7(this,new J7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.uM,b,(b.H.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.Yt,b))};
g.h.RD=function(a){if(!this.ma()){M7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)M7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),O7(this,new I7(this.A,b),!0);else{this.hc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=y6(this.A.te(),c.label);
d&&t6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(M7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.ff(this.o),this.o=new I7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.SD,this,this.o)),this.o.tk(null));this.o.gw(a)}}};
g.h.NX=function(){return this.o?this.o.nG():null};
g.h.MU=function(a){this.ma()||(this.hc("Failed to estabilish a session: "+g.Ig(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&O7(this,null))};
g.h.rU=function(a){M7("Receiver availability updated: "+a);if(!this.ma()){var b=N7(this);this.D=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;N7(this)!=b&&this.V("yt-remote-cast2-availability-change",N7(this))}};
g.h.mG=function(){this.ma()||(this.B=JEa(this),M7("Updating custom receivers: "+g.Ig(this.B)),window.chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.hc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",N7(this)))};
L7.prototype.setLaunchParams=L7.prototype.EW;L7.prototype.setConnectedScreenStatus=L7.prototype.DW;L7.prototype.stopSession=L7.prototype.OX;L7.prototype.getCastSession=L7.prototype.NX;L7.prototype.requestSession=L7.prototype.requestSession;L7.prototype.init=L7.prototype.init;L7.prototype.dispose=L7.prototype.dispose;var U7=[];g.h=Z7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";$7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.o=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.A=a.trackData,this.dg=a.hasPrevious,this.hasNext=a.hasNext,this.H=a.playerTime,this.G=a.playerTimeAt,this.D=a.seekableStart,this.B=a.seekableEnd,this.J=a.duration,this.K=a.loadedTime,this.C=a.liveIngestionTime,this.F=!(0,window.isNaN)(this.C))};
g.h.qb=function(){return 1==this.o};
g.h.isAdPlaying=function(){return 1081==this.o};
g.h.getDuration=function(){return this.F?this.J+a8(this):this.J};
g.h.clone=function(){return new Z7(e8(this))};g.B(g8,g.RF);g.h=g8.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,m8(this,"play")):l8(this,"play"),k8(this,1,c8(h8(this))),this.V("remotePlayerChange")):i8(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,m8(this,"pause")):l8(this,"pause"),k8(this,2,c8(h8(this))),this.V("remotePlayerChange")):i8(this,this.pause)};
g.h.iG=function(a){if(1==this.o){if(this.A){var b=h8(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.o?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,m8(this,"seekTo",{newTime:a}))}else l8(this,"seekTo",{newTime:a});k8(this,3,a);this.V("remotePlayerChange")}else i8(this,g.Fa(this.iG,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,m8(this,"stopVideo")):l8(this,"stopVideo");var a=h8(this);a.index=-1;a.videoId="";$7(a);j8(this,a);this.V("remotePlayerChange")}else i8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=h8(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){q7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.hc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){q7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.hc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);l8(this,"setVolume",e)}c.muted=b;c.volume=a;j8(this,c)}else i8(this,g.Fa(this.setVolume,a,b))};
g.h.iF=function(a,b){if(1==this.o){var c=h8(this),d={videoId:a};b&&(c.A={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Ig(b.style),g.hc(d,c.A));l8(this,"setSubtitlesTrack",d);j8(this,c)}else i8(this,g.Fa(this.iF,a,b))};
g.h.Ww=function(a,b){if(1==this.o){l8(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jb.id});var c=h8(this);c.audioTrackId=b.Jb.id;j8(this,c)}else i8(this,g.Fa(this.Ww,a,b))};
g.h.hG=function(a,b){if(1==this.o){if(a&&b){var c=h8(this);d8(c,a,b);j8(this,c)}l8(this,"previous")}else i8(this,g.Fa(this.hG,a,b))};
g.h.gG=function(a,b){if(1==this.o){if(a&&b){var c=h8(this);d8(c,a,b);j8(this,c)}l8(this,"next")}else i8(this,g.Fa(this.gG,a,b))};
g.h.oz=function(){1==this.o?l8(this,"dismissAutoplay"):i8(this,this.oz)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}g8.ea.dispose.call(this)};
g.h.X=function(){WEa(this);this.C=null;this.D.clear();f8(this,null);g8.ea.X.call(this)};
g.h.Xw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.AC(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.iU=function(a,b){this.V(a,b)};
g.h.HR=function(a){if(!a)this.Pm(null),f8(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=h8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)q7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,j8(this,b)}};
g.h.Pm=function(a){q7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),XEa(this),this.V("remotePlayerChange")};
g.h.GR=function(a){a?(XEa(this),this.V("remotePlayerChange")):this.Pm(null)};
g.h.TR=function(){var a=TEa();a&&f8(this,a)};
g.h.hc=function(a){q7("CP",a)};g.B(n8,g.RF);g.h=n8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.u(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.u(k)&&(l.currentIndex=k);c&&(this.fb.listId=c);this.fb.videoId=d;this.fb.index=k||0;this.fb.state=3;b8(this.fb,m);this.C="UNSUPPORTED";o8("Connecting with setPlaylist and params: "+g.Ig(l));this.o.connect({method:"setPlaylist",
params:g.Ig(l)},a,sDa())}else o8("Connecting without params"),this.o.connect({},a,sDa());ZEa(this)};
g.h.dispose=function(){this.ma()||(this.V("beforeDispose"),p8(this,3));n8.ea.dispose.call(this)};
g.h.X=function(){q8(this);s8(this);r8(this);g.iE(this.J);this.J=window.NaN;g.iE(this.K);this.K=window.NaN;this.B=null;g.BF(this.T);this.T.length=0;this.o.dispose();n8.ea.X.call(this);this.C=this.G=this.A=this.fb=this.o=null};
g.h.HK=function(){this.F(2)};
g.h.LR=function(){o8("Channel opened");this.O&&(this.O=!1,r8(this),this.M=g.gE((0,g.A)(function(){o8("Timing out waiting for a screen.");this.F(1)},this),15E3));
wDa(iEa(this.o),this.ba)};
g.h.IR=function(){o8("Channel closed");(0,window.isNaN)(this.D)?D6(!0):D6();this.dispose()};
g.h.JR=function(a){D6();(0,window.isNaN)(this.H())?(o8("Channel error: "+a+" without reconnection"),this.dispose()):(this.O=!0,o8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),p8(this,2))};
g.h.KR=function(a){a.params?o8("Received: action="+a.action+", params="+g.Ig(a.params)):o8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.hx(a.params.devices);this.A=(0,g.I)(a,function(a){return new r6(a)});
a=!!g.Ka(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
bFa(this,a);break;case "loungeScreenDisconnected":g.Ua(this.A,function(a){return"LOUNGE_SCREEN"==a.type});
bFa(this,!1);break;case "remoteConnected":var b=new r6(g.hx(a.params.device));g.Ka(this.A,function(a){return b?a.id==b.id:!1})||g.Ra(this.A,b);
break;case "remoteDisconnected":b=new r6(g.hx(a.params.device));g.Ua(this.A,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":dFa(this,a);break;case "nowPlaying":fFa(this,a);break;case "onStateChange":eFa(this,a);break;case "onAdStateChange":gFa(this,a);break;case "onVolumeChanged":hFa(this,a);break;case "onSubtitlesTrackChanged":cFa(this,a);break;case "nowAutoplaying":iFa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":jFa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:o8("Unrecognized action: "+a.action)}};
g.h.mW=function(){if(this.B){var a=this.B;this.B=null;this.fb.videoId!=a&&t8(this,"getNowPlaying")}};
n8.prototype.subscribe=n8.prototype.subscribe;n8.prototype.unsubscribeByKey=n8.prototype.Yd;n8.prototype.ia=function(){var a=3;this.ma()||(a=0,(0,window.isNaN)(this.H())?l7(this.o)&&(0,window.isNaN)(this.D)&&(a=1):a=2);return a};
n8.prototype.getProxyState=n8.prototype.ia;n8.prototype.F=function(a){o8("Disconnecting with "+a);q8(this);this.V("beforeDisconnect",a);1==a&&D6();jEa(this.o,a);this.dispose()};
n8.prototype.disconnect=n8.prototype.F;n8.prototype.ha=function(){var a=this.fb;this.B&&(a=this.fb.clone(),d8(a,this.B,a.index));return e8(a)};
n8.prototype.getPlayerContextData=n8.prototype.ha;
n8.prototype.oa=function(a){var b=new Z7(a);b.videoId&&b.videoId!=this.fb.videoId&&(this.B=b.videoId,g.iE(this.J),this.J=g.gE((0,g.A)(this.mW,this),5E3));var c=[];this.fb.listId==b.listId&&this.fb.videoId==b.videoId&&this.fb.index==b.index||c.push("remoteQueueChange");this.fb.o==b.o&&this.fb.volume==b.volume&&this.fb.muted==b.muted&&c8(this.fb)==c8(b)&&g.Ig(this.fb.A)==g.Ig(b.A)||c.push("remotePlayerChange");this.fb.reset(a);(0,g.C)(c,function(a){this.V(a)},this)};
n8.prototype.setPlayerContextData=n8.prototype.oa;n8.prototype.Z=function(){var a=this.o.F.id,b=g.Ka(this.A,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
n8.prototype.getOtherConnectedRemoteId=n8.prototype.Z;n8.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.G)():window.NaN};
n8.prototype.getReconnectTimeout=n8.prototype.H;n8.prototype.aa=function(){return this.C||"UNSUPPORTED"};
n8.prototype.getAutoplayMode=n8.prototype.aa;n8.prototype.da=function(){return this.G||""};
n8.prototype.getAutoplayVideoId=n8.prototype.da;n8.prototype.va=function(){if(!(0,window.isNaN)(this.H())){var a=this.o.A;g.ku(a.o);a.start()}};
n8.prototype.reconnect=n8.prototype.va;n8.prototype.ka=function(a,b){t8(this,a,b);aFa(this)};
n8.prototype.sendMessage=n8.prototype.ka;g.B(u8,u7);g.h=u8.prototype;g.h.te=function(a){return this.hd.$_gs(a)};
g.h.contains=function(a){return!!this.hd.$_c(a)};
g.h.get=function(a){return this.hd.$_g(a)};
g.h.start=function(){this.hd.$_st()};
g.h.add=function(a,b,c){this.hd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.hd.$_r(a,b,c)};
g.h.Wq=function(a,b,c,d){this.hd.$_un(a,b,c,d)};
g.h.X=function(){for(var a=0,b=this.A.length;a<b;++a)this.hd.$_ubk(this.A[a]);this.A.length=0;this.hd=null;u8.ea.X.call(this)};
g.h.KX=function(){this.V("screenChange")};
g.h.HT=function(){this.V("onlineScreenChange")};
D7.prototype.$_st=D7.prototype.start;D7.prototype.$_gspc=D7.prototype.LX;D7.prototype.$_gsppc=D7.prototype.lG;D7.prototype.$_c=D7.prototype.contains;D7.prototype.$_g=D7.prototype.get;D7.prototype.$_a=D7.prototype.add;D7.prototype.$_un=D7.prototype.Wq;D7.prototype.$_r=D7.prototype.remove;D7.prototype.$_gs=D7.prototype.te;D7.prototype.$_gos=D7.prototype.kG;D7.prototype.$_s=D7.prototype.subscribe;D7.prototype.$_ubk=D7.prototype.Yd;var v8=null,w8=null,L8=null,A8=[];g.t(M8,g.M);g.h=M8.prototype;
g.h.X=function(){g.M.prototype.X.call(this);this.C.stop();this.D.stop();this.L.stop();this.O();this.o.unsubscribe("proxyStateChange",this.OD,this);this.o.unsubscribe("remotePlayerChange",this.Sm,this);this.o.unsubscribe("remoteQueueChange",this.bq,this);this.o.unsubscribe("autoplayUpNext",this.mD,this);this.o.unsubscribe("previousNextChange",this.LD,this);this.o.unsubscribe("nowAutoplaying",this.DD,this);this.o.unsubscribe("autoplayDismissed",this.lD,this);this.o=this.H=null};
g.h.nC=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(P8(this)){if(!h8(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":h8(this.o).qb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.ak(c[0],c[1]);break;case "control_subtitles_set_track":Q8(this,c[0]);break;case "control_set_audio_track":c=c[0],P8(this)&&this.o.Ww(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();R8(this,0==c?void 0:c);break;case "control_seek":R8(this,c[0]);break;case "control_subtitles_set_track":Q8(this,c[0]);break;case "control_set_audio_track":c=c[0],P8(this)&&this.o.Ww(this.A.getVideoData(1).videoId,c)}};
g.h.FR=function(a){this.L.CK(a)};
g.h.lX=function(a){this.nC("control_subtitles_set_track",g.Zb(a)?null:a)};
g.h.yF=function(){var a=this.A.Ac("captions","track");g.Zb(a)||Q8(this,a)};
g.h.BD=function(a){if(P8(this)){this.o.unsubscribe("remotePlayerChange",this.Sm,this);var b=Math.round(a.volume);a=!!a.muted;var c=h8(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Sm,this)}};
g.h.aT=function(){g.Zb(this.F)||vFa(this,this.F);this.G=!1};
g.h.OD=function(a,b){this.D.stop();2==b&&this.vF()};
g.h.Sm=function(){if(P8(this)){this.C.stop();var a=h8(this.o);switch(a.o){case 1081:case 1:O8(this,new g.pQ(8));this.uF();break;case 1085:case 3:O8(this,new g.pQ(9));break;case 1083:case 0:O8(this,new g.pQ(2));this.K.stop();N8(this,this.A.getVideoData().lengthSeconds);break;case 1084:O8(this,new g.pQ(4));break;case 2:O8(this,new g.pQ(4));N8(this,c8(a));break;case -1:O8(this,new g.pQ(64));break;case -1E3:O8(this,new g.pQ(128,{errorCode:"mdx.remoteerror",message:"Denne videoen er ikke tilgjengelig for ekstern avspilling."}))}a=
h8(this.o).A;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,vFa(this,a));a=h8(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.UF()}else uFa(this)};
g.h.LD=function(){this.A.V("mdxpreviousnextchange")};
g.h.bq=function(){P8(this)||uFa(this)};
g.h.IJ=function(){this.o.oz()};
g.h.mD=function(a){a&&(a=g.xE("/watch_queue_ajax",{method:"GET",bd:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.mV,this)}))&&(this.O=(0,g.A)(a.abort,a))};
g.h.mV=function(a,b){var c=new g.iP({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.DD=function(a){(0,window.isNaN)(a)||this.A.V("mdxnowautoplaying",a)};
g.h.lD=function(){this.A.V("mdxautoplaycanceled")};
g.h.DP=function(a,b){-1==h8(this.o).o?R8(this,a):b&&this.o.iG(a)};
g.h.UF=function(){if(P8(this)){var a=h8(this.o);this.B.Ha(this.T);a.muted?this.A.mute():this.A.lg();this.A.setVolume(a.volume);this.T=this.B.R(this.A,"onVolumeChange",this.BD)}};
g.h.uF=function(){this.C.stop();if(!this.o.ma()){var a=h8(this.o);a.qb()&&O8(this,new g.pQ(8));N8(this,c8(a));this.C.start()}};
g.h.vF=function(){this.D.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!(0,window.isNaN)(a)&&this.D.start()};g.t(S8,g.W);S8.prototype.D=function(a){xFa(this,a.state)};g.t(T8,g.nZ);T8.prototype.L=function(){var a=this.A.Ac("remote","receivers");a&&1<a.length&&!this.A.Ac("remote","quickCast")?(this.J=g.kb(a,this.F,this),g.oZ(this,(0,g.I)(a,this.F)),a=this.A.Ac("remote","currentReceiver"),this.Bf(this.F(a)),this.enable(!0)):this.enable(!1)};
T8.prototype.F=function(a){return a.key};
T8.prototype.Af=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
T8.prototype.yd=function(a){g.nZ.prototype.yd.call(this,a);this.A.Td("remote","currentReceiver",this.J[a]);this.D.Sb()};g.t(U8,g.JU);g.h=U8.prototype;g.h.create=function(){oFa(g.mN(g.Y(this.o)));this.F.push(g.cG("yt-remote-before-disconnect",this.AR,this));this.F.push(g.cG("yt-remote-connection-change",this.sU,this));this.F.push(g.cG("yt-remote-receiver-availability-change",this.MD,this));this.F.push(g.cG("yt-remote-auto-connect",this.qU,this));this.F.push(g.cG("yt-remote-receiver-resumed",this.pU,this));this.MD()};
g.h.load=function(){this.o.Ru();g.JU.prototype.load.call(this);this.D=new M8(this,this.o,this.A);var a=(a=tFa())?a.currentTime:0;var b=K8()?new g8(F8(),void 0):null;0==a&&b&&(a=c8(h8(b)));0!=a&&(this.J=a||0,this.o.V("progresssync",a,void 0));wFa(this,this.G,this.G);g.L_(this.o.app,6)};
g.h.unload=function(){this.o.V("mdxautoplaycanceled");this.C=this.B;g.gf(this.D,this.A);this.A=this.D=null;g.JU.prototype.unload.call(this);g.L_(this.o.app,5)};
g.h.X=function(){g.dG(this.F);g.JU.prototype.X.call(this)};
g.h.Im=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.D.nC.apply(this.D,[a].concat(g.oa(c)))};
g.h.xK=function(){return this.loaded?this.D.suggestion:null};
g.h.dg=function(){return this.A?h8(this.A).dg:!1};
g.h.hasNext=function(){return this.A?h8(this.A).hasNext:!1};
g.h.getCurrentTime=function(){return this.J};
g.h.rP=function(){var a=h8(this.A),b=this.o.getVideoData();return{allowSeeking:this.o.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.F?a.C+a8(a):a.C,isPeggedToLive:1>=(a.F?a.B+a8(a):a.B)-this.getCurrentTime(),loaded:a.K,seekableEnd:a.F?a.B+a8(a):a.B,seekableStart:0<a.D?a.D+a8(a):a.D}};
g.h.sP=function(){this.A&&this.A.gG()};
g.h.tP=function(){this.A&&this.A.hG()};
g.h.AR=function(a){1==a&&(this.K=this.A?h8(this.A):null)};
g.h.sU=function(){var a=K8()?new g8(F8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.A=a;this.K=null;b.key!=this.B.key&&(this.C=b,this.load())}else g.ff(this.A),this.A=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.o.getVideoData().videoId&&this.o.RB(a.videoId,c8(a)));this.o.V("videodatachange","newdata",this.o.getVideoData(),3)};
g.h.MD=function(){this.H=[this.B].concat(qFa());var a=G8()||this.B;V8(this,a);this.o.xa("onMdxReceiversChange")};
g.h.qU=function(){var a=G8();V8(this,a)};
g.h.pU=function(){this.C=G8()};
g.h.qP=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?X7():V8(this,b)),this.loaded?this.C:this.B;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&X7(),!0):!1}};
g.h.uP=function(){l8(this.A,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Dc=function(){return!1};g.AX.remote=U8;})(_yt_player);
